<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_Update_undefined_var_table extends CI_Migration {

	public function up()
	{
		mysql_query("TRUNCATE TABLE `undefined_var`");
		mysql_query("INSERT INTO  `fantoon_ci`.`undefined_var` ( `id` , `view_page` , `variable`) VALUES
			( NULL , 'views/admin/alpha_users.php', ''),
			( NULL , 'views/admin/transfer.php', ''),
			( NULL , 'views/admin/admin.php', ''),
			( NULL , 'views/privacy/privacy.php', ''),
			( NULL , 'views/index.php', ''),
			( NULL , 'views/chat/chat.php', ''),
			( NULL , 'views/email_templates/invite_friends_template.php', ''),
			( NULL , 'views/email_templates/sxsw_invite.php', ''),
			( NULL , 'views/email_templates/newsletter_template.php', ''),
			( NULL , 'views/email_templates/collaboration_newsfeed_template.php', ''),
			( NULL , 'views/email_templates/up_template.php', ''),
			( NULL , 'views/email_templates/email_footer_unsubscribe.php', ''),
			( NULL , 'views/email_templates/signup_thanks_template.php', ''),
			( NULL , 'views/email_templates/common_template.php', ''),
			( NULL , 'views/email_templates/reply_template.php', ''),
			( NULL , 'views/email_templates/collaborator_email_template.php', ''),
			( NULL , 'views/email_templates/follow_list_template.php', ''),
			( NULL , 'views/email_templates/temp_newsletter.php', ''),
			( NULL , 'views/email_templates/resetpassword_template.php', ''),
			( NULL , 'views/email_templates/comment_template.php', ''),
			( NULL , 'views/email_templates/alpha_invite_template.php', ''),
			( NULL , 'views/email_templates/follow_folder_template.php', ''),
			( NULL , 'views/email_templates/welcome_template.php', ''),
			( NULL , 'views/email_templates/email_header.php', ''),
			( NULL , 'views/email_templates/collaborator_template.php', ''),
			( NULL , 'views/email_templates/connection_template.php', ''),
			( NULL , 'views/email_templates/email_header_fancy.php', ''),
			( NULL , 'views/email_templates/message_template.php', ''),
			( NULL , 'views/email_templates/email_footer.php', ''),
			( NULL , 'views/email_templates/mention_template.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_get_link_postbox.php', ''),
			( NULL , 'modules/sxsw/views/twitter_logged_in.php', ''),
			( NULL , 'modules/sxsw/views/up_template.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_post_login.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_email_3.php', ''),
			( NULL , 'modules/sxsw/views/comment_template.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_submit_link_popup.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_post_notification.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_email_1.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_email_2.php', ''),
			( NULL , 'modules/sxsw/views/unsubscribe.php', ''),
			( NULL , 'modules/user_location/views/links_details.php', ''),
			( NULL , 'modules/newsfeed/views/filter_types_menu.php', ''),
			( NULL , 'modules/newsfeed/views/newsfeed_delete_popup.php', ''),
			( NULL , 'modules/embed/views/collection_no_exist.php', ''),
			( NULL , 'modules/fantoon-extensions/views/includes/info_dialog.php', ''),
			( NULL , 'modules/fantoon-extensions/views/includes/footer_external.php', ''),
			( NULL , 'modules/fantoon-extensions/views/includes/header_external.php', ''),
			( NULL , 'modules/admin/views/layout.php', ''),
			( NULL , 'modules/admin/views/source_stats.php', ''),
			( NULL , 'modules/admin/views/alpha_invite_template.php', ''),
			( NULL , 'modules/admin/views/users/settings_view.php', ''),
			( NULL , 'modules/admin/views/users/create_user.php', ''),
			( NULL , 'modules/admin/views/auth/index.php', ''),
			( NULL , 'modules/admin/views/home.php', ''),
			( NULL , 'modules/admin/views/stats/general.php', ''),
			( NULL , 'modules/admin/views/stats/chart_bar.php', ''),
			( NULL , 'modules/admin/views/stats/chart_line.php', ''),
			( NULL , 'modules/admin/views/stats/chart_pie.php', ''),
			( NULL , 'modules/signup/views/twitter_logged_in.php', ''),
			( NULL , 'modules/signup/views/signup_error.php', ''),
			( NULL , 'modules/signup/views/login.php', ''),
			( NULL , 'modules/tools/views/test_url.php', ''),
			( NULL , 'modules/footer/views/about_team_spec.php', ''),
			( NULL , 'modules/footer/views/contact_us.php', ''),
			( NULL , 'modules/footer/views/successful_contact.php', ''),
			( NULL , 'modules/footer/views/about_terms.php', ''),
			( NULL , 'modules/footer/views/about_team.php', ''),
			( NULL , 'modules/footer/views/about_main.php', ''),
			( NULL , 'modules/footer/views/about_privacy.php', ''),
			( NULL , 'modules/footer/views/about_contactus.php', ''),
			( NULL , 'modules/footer/views/about_copyright.php', ''),
			( NULL , 'modules/footer/views/contact_form.php', ''),
			( NULL , 'modules/footer/views/about_jobs.php', ''),
			( NULL , 'modules/forget_password/views/forgetpassword_view.php', ''),
			( NULL , 'modules/forget_password/views/forgetpassword_step2.php', ''),
			( NULL , 'modules/profile/views/twitter_connected.php', ''),
			( NULL , 'modules/profile/views/no_profile.php', ''),
			( NULL , 'modules/profile/views/invite_popup.php', ''),
			( NULL , 'modules/profile/views/yahoo_after.php', ''),
			( NULL , 'modules/profile/views/gmail.auth.php', ''),
			( NULL , 'modules/profile/views/landing_page/landing_page_old.php', ''),
			( NULL , 'modules/profile/views/landing_page/landing_page_top.php', ''),
			( NULL , 'modules/profile/views/landing_page/landing_page_top_new.php', ''),
			( NULL , 'modules/profile/views/de_profile.php', ''),
			( NULL , 'modules/profile/views/invite_gmail.php', ''),
			( NULL , 'modules/profile/views/invite_page.php', ''),
			( NULL , 'modules/profile/views/gmail_after.php', ''),
			( NULL , 'modules/profile/views/unsubscribe.php', ''),
			( NULL , 'modules/link/views/popup.php', ''),
			( NULL , 'modules/api/views/test_page.php', ''),
			( NULL , 'modules/help/views/walkthrough_discovery.php', ''),
			( NULL , 'modules/help/views/walkthrough_home.php', ''),
			( NULL , 'modules/help/views/walkthrough_profile.php', ''),
			( NULL , 'modules/help/views/walkthrough_interest.php', ''),
			( NULL , 'modules/help/views/walkthrough_start.php', ''),
			( NULL , 'modules/folder/views/delete_collection_popup.php', ''),
			( NULL , 'modules/folder/views/folder_embed_popup.php', ''),
			( NULL , 'modules/migrate/views/actions_view.php', ''),
			( NULL , 'modules/bookmarklet/views/share_drop_on_fb.php', ''),
			( NULL , 'modules/bookmarklet/views/walkthrough.php', ''),
			( NULL , 'views/list/list_newsfeed.php' , 'stage,num_interests,page_array,list_info[0][''list_name''],check_list_user,list_info[0][''list_id'']'),
			( NULL , 'views/custom_tab/custom_tab.php' , 'owner_priv,admin_priv,tab[0][''activated''],tab,tab_content'),
			( NULL , 'views/badge/badge.php' , 'type,user->id,user->user_stats[0]->total_drops,user->user_stats[0]->likes,user->url,user->avatar_badge,user->first_name,user->last_name,collections_number,user->drops_url,user->likes_url,check_friends,page_info[''page_id''],page_info[''thumbnail''],page_info[''interest_id''],page_info[''uri_name''],link_disable,in,page_info[''page_name''],page_description,page_info[''hits''],page_users'),
			( NULL , 'views/photos/albums.php' , 'profile_id,my_data[''first_name''],my_data[''last_name''],page_id,albums,id,myphotos_count,myphotos_thumb'),
			( NULL , 'views/photos/show_photo.php' , 'album_info[0][''album_name''],album_photos,photos_array,photo_info[0][0][''photo_name''],photo_info[0][0][''photo_caption'']'),
			( NULL , 'views/photos/photos.php' , 'ajax,album[0][''album_name''],photos,pid'),
			( NULL , 'views/admin/admin_questions.php' , 'questions'),
			( NULL , 'views/admin/admin_aliases.php' , 'aliases'),
			( NULL , 'views/admin/admin_pages.php' , 'pages'),
			( NULL , 'views/admin/edit_question.php' , 'question'),
			( NULL , 'views/event/events.php' , 'display_type,view_type,events,eid,owner_priv,admin_priv,v,v[''event_id''],invitees,v[''user_link''],show_comments,page_users'),
			( NULL , 'views/event/edit_event.php' , 'event'),
			( NULL , 'views/home/home_update_friends.php' , 'newsfeeds,view_type,page_id,post_type,profile_id,fvalue'),
			( NULL , 'views/home/newsfeed_layout/magazine.php' , 'mag_lay->rend_social,most_recent_timestamp'),
			( NULL , 'views/home/newsfeed_layout/magazine1.php' , 'items'),
			( NULL , 'views/home/home_update_interest.php' , 'view,view_layout,newsfeeds,mag_lay->rend_arr'),
			( NULL , 'views/home/home_main.php' , 'category_type,topic->topic_name,topics,topic_uri_name,drop_type,ticker,loops'),
			( NULL , 'views/home/home_update_activity.php' , 'ticker,view_type'),
			( NULL , 'views/home/home.php' , 'include_file'),
			( NULL , 'views/search/search_index_results.php' , 'welcome_msg'),
			( NULL , 'views/search/search_drops_results.php' , 'category_type,stage,profile_id'),
			( NULL , 'views/search/search_results.php' , 'search_category,inner_view'),
			( NULL , 'views/search/search_topics_results.php' , 'results'),
			( NULL , 'views/search/search_collections_results.php' , 'autoscroll,results,loadmore'),
			( NULL , 'views/loop/loops_view.php' , 'circle_element,s],avatar,friendname,circlename,circle_order,circlebox,c,c[''left''],c[''top''],friendbox,c[''cid'']'),
			( NULL , 'views/loop/edit_loop.php' , 'loop_id,loop_info[''loop_name''],my_connections,my_follow'),
			( NULL , 'views/loop/loop.php' , 'view_type,feeds_array,value[''type''],news_array[0],news_array[1]'),
			( NULL , 'views/error.php' , 'error,descripion'),
			( NULL , 'views/chat/main_page.php' , 'myname,selfonline,soundmute,havefriend,friendlistid,friendlist_name,user'),
			( NULL , 'views/pr/pr.php' , 'owner_priv,admin_priv,pr_lock,pr_error,prs,view_type'),
			( NULL , 'views/recommendations/recommender.php' , 'methodName'),
			( NULL , 'views/recommendations/gen_similarity_finish.php' , 'title,content'),
			( NULL , 'modules/topics/views/topic_more_interests.php' , 'pages,loaded_pages'),
			( NULL , 'modules/topics/views/topic_new_entry.php' , 'path,node_id,node_name,current_id'),
			( NULL , 'modules/topics/views/topic_feeds.php' , 'topic_id,page_id,topic_name,stage,source,include_file,main_pic,topic_pages,hits'),
			( NULL , 'modules/topics/views/topic_page.php' , 'topic_name,user_id,topic_aliases,merge_topics,parent_id,child_id,path'),
			( NULL , 'modules/topics/views/topic_newsfeed.php' , 'feeds_array'),
			( NULL , 'modules/topics/views/topic_delete.php' , 'path'),
			( NULL , 'modules/topics/views/topic_new_alias.php' , 'alias_name,topic_id,alias_id'),
			( NULL , 'modules/topics/views/topic_organize.php' , 'topic_name,user_id,topic_aliases,merge_topics,parent_id,child_id,path'),
			( NULL , 'modules/topics/views/topic_interests.php' , 'pages,loaded_pages'),
			( NULL , 'modules/topics/views/edit_picture.php' , 'topic_id,topic_name'),
			( NULL , 'modules/topics/views/topic_info.php' , 'topic_name,pages,config,sizes,tree_str'),
			( NULL , 'modules/interests/views/page_new_feature_edit.php' , 'page_info,page_id'),
			( NULL , 'modules/interests/views/page_info.php' , 'type_form[0],info[''address''],info[''city''],info[''zip''],info[''phone''],info[''email''],info[''founded''],info[''about''],info[''description''],info[''website''],info[''product''],info[''hour''],info[''food_served''],info[''specialty''],info[''food''],info[''interest''],info[''gender''],info[''birthday''],info[''biograph''],info[''current_location''],info,info[''release_date''],info[''record_label''],info[''manager_name''],info[''booking_agent''],info[''press_contact''],info[''influence''],info[''hometown''],info[''award''],info[''label_record''],info[''member''],info[''schedule''],info[''genre''],info[''written_by''],info[''isbn''],info[''directed_by''],info[''starring'']'),
			( NULL , 'modules/interests/views/page_sidebar.php' , 'main_pic,mod_priv,editor_priv'),
			( NULL , 'modules/interests/views/page_info_common.php' , 'info[''interest''],info[''gender''],info[''birthday''],info[''hometown''],info[''biograph''],info[''phone''],info[''email''],info[''current_location''],info[''about''],info[''description''],info[''website''],info[''college''],info[''manager_name''],info[''booking_agent''],info[''press_contact''],info[''award'']'),
			( NULL , 'modules/interests/views/fans_section_img.php' , 'value[''thumbnail''],value[''gender''],value[''uri_name''],value[''user_id''],value[''first_name''],value[''last_name''],your_connection_ids'),
			( NULL , 'modules/interests/views/feature_page_edit.php' , 'page_info[0][''page_name''],page_info[0][''uri_name''],page_info[0][''page_id''],page_info[0][''owner_id''],admin_priv,editor_priv,page_id,featured_dropdown,feature_pages'),
			( NULL , 'modules/interests/views/page_topics.php' , 'topic_list,page_id'),
			( NULL , 'modules/interests/views/page.php' , 'page_id,page_info[0][''topic_lock''],page_info[0][''uri_name''],page_info[0][''page_name''],owner_priv,admin_priv,mod_priv,editor_priv,in,fans,uri_name,record,include_file,page->avatar,page_info[0][''hits''],myself[''thumbnail''],myself[''gender''],myself[''uri_name''],myself[''id''],record_in_follower,record_in_following,record_out'),
			( NULL , 'modules/interests/views/register_page.php' , 'error'),
			( NULL , 'modules/interests/views/page_fans.php' , 'in,your_connection_ids'),
			( NULL , 'modules/interests/views/feature_interests.php' , 'feature_pages'),
			( NULL , 'modules/interests/views/community_edit_common.php' , 'item[''uri_name''],item[''user_id''],item[''gender''],item[''first_name''],item[''last_name''],owner_priv,page_id,admin_priv,item[''role''],mod_priv'),
			( NULL , 'modules/interests/views/edit_picture.php' , 'page->avatar,page->page_id,page->page_name'),
			( NULL , 'modules/interests/views/community_edit.php' , 'page_info[0][''page_name''],page_info[0][''uri_name''],page_info[0][''page_id''],owner,owner_priv,admin_priv,page_id,mod_priv,admin,mod,fan'),
			( NULL , 'modules/interests/views/page_wall.php' , 'page_info[0][''official_url''],page_info[0][''uri_name''],page_info[0][''page_id''],page_info[0][''page_name''],threads,page_id,owner_priv,admin_priv,newsfeeds,feeds_array'),
			( NULL , 'modules/interests/views/page_new_feature.php' , 'page_info'),
			( NULL , 'modules/interests/views/edit_page_info.php' , 'page_info[0][''page_name''],page_info[0][''uri_name''],page_info[0][''page_id''],page_info[0][''cid''],categories_all,interest_categories,type_form[0][''interest_id''],type_form[0][''form''],info[0][''address''],info[0][''city''],info[0][''zip''],info[0][''phone''],info[0][''email''],info[0][''founded''],info[0][''about''],info[0][''description''],info[0][''website''],info[0][''product''],info[0][''hour''],info[0][''interest''],info[0][''gender''],info[0][''birthday''],info[0][''hometown''],info[0][''biograph''],info[0][''current_location''],info[0][''college''],info[0][''award''],info[0][''release_date''],info[0][''member''],info[0][''record_label''],info[0][''manager_name''],info[0][''booking_agent''],info[0][''press_contact''],info[0][''influence''],info[0][''label_record''],info[0][''schedule''],info[0][''genre''],info[0][''written_by''],info[0][''isbn''],info[0][''directed_by''],info[0][''starring''],page_id'),
			( NULL , 'modules/interests/views/page_wizard.php' , 'role,categories'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_tile.php' , 'view,item->sxsw_likes,item->id,item->like_count,item->link_url,item->uniqid,item->title,item->image,item->comment_count,item->sxsw_user->id,item->sxsw_user->thumbnail,item->sxsw_user->first_name,item->sxsw_user->last_name,item->category,item->time,item->get,item->sxsw_comments'),
			( NULL , 'modules/sxsw/views/sxsw_link_popup.php' , 'item->id,item->sxsw_likes,item->media,item->link_url,item->image,item->title,title,item->uniqid,item->sxsw_user->id,item->sxsw_user->thumbnail,item->sxsw_user->first_name,item->sxsw_user->last_name,item->time,item->comment_count,item->get'),
			( NULL , 'modules/sxsw/views/sxsw_up_view.php' , 'ci->session,cv->sxsw_comment_likes,item->sxsw_likes,item->id,cv->id'),
			( NULL , 'modules/sxsw/views/sxsw_external_connect.php' , 'is_post,fb_id,twitter_id'),
			( NULL , 'modules/sxsw/views/sxsw_user.php' , 'twitter_id,fb_id,full_name,signup_url,user->id,link_type,user->thumbnail,user->first_name,user->last_name,link_count,comment_count,like_count,view_type,category,uniqid,item->title'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_timeline.php' , 'item->sxsw_likes,item->link_url,view,item->id,item->sxsw_user->id,item->sxsw_user->thumbnail,item->sxsw_user->first_name,item->sxsw_user->last_name,item->time,item->category,item->uniqid,item->like_count,item->image,item->get,session->userdata,item->comment_count'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_tile_list.php' , 'links,category,user->id,link_type'),
			( NULL , 'modules/sxsw/views/sxsw_index.php' , 'twitter_id,fb_id,full_name,signup_url,view_type,category,uniqid,item->title'),
			( NULL , 'modules/sxsw/views/sxsw_likes.php' , 'likes'),
			( NULL , 'modules/sxsw/views/sxsw_all_comments.php' , 'item->sxsw_likes,item->sxsw_user->id,item->sxsw_user->thumbnail,item->sxsw_user->first_name,item->sxsw_user->last_name,item->time,item->comment_count,item->id,item->get'),
			( NULL , 'modules/sxsw/views/sxsw_post_link.php' , 'category_dropdown,links,photos'),
			( NULL , 'modules/sxsw/views/sxsw_fandrop_aftersignup.php' , 'email_count'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_timeline_newcomment.php' , 'comment->id,comment->sxsw_user->thumbnail,comment->user_id,comment->sxsw_user->id,comment->sxsw_user->first_name,comment->sxsw_user->last_name,comment->comment,comment->time,comment,comment->sxsw_comment_likes,session->userdata'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_tile_newcomment.php' , 'comment->id,comment->sxsw_user->id,comment->sxsw_user->thumbnail,comment->sxsw_user->first_name,comment->sxsw_user->last_name,comment->comment'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_full_newcomment.php' , 'comment->id,comment->user_id,comment->sxsw_user->id,comment->sxsw_user->thumbnail,comment->sxsw_user->first_name,comment->sxsw_user->last_name,comment->time,comment->comment,comment'),
			( NULL , 'modules/sxsw/views/sxsw_fandrop_signup.php' , 'error_msg'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_timeline_list.php' , 'links,category,user->id,link_type'),
			( NULL , 'modules/list/views/list_edit.php' , 'list_info[0][''list_name''],list_info[0][''list_id''],list_info[0][''description''],list_info[0][''visibility'']'),
			( NULL , 'modules/list/views/show_lists.php' , 'my_lists,following_lists,profile_id,my_data[''first_name'']'),
			( NULL , 'modules/list/views/page_lists.php' , 'page_lists,following_lists,page_name[''page_name''],profile_id'),
			( NULL , 'modules/list/views/list_view.php' , 'friendname,circlebox,circle_order,circlename,avatar,friendbox,circle_element,s'),
			( NULL , 'modules/list/views/list_newsfeed.php' , 'num_interests,page_array,called_by'),
			( NULL , 'modules/list/views/list.php' , 'my_pages'),
			( NULL , 'modules/system_notification/views/system_notification_view.php' , 'notification->title,notification->content'),
			( NULL , 'modules/discover_interests/views/discover_interests.php' , 'my_interests,interest_categories,value,value[''id''],value[''type''],interests,page_ids'),
			( NULL , 'modules/discover_interests/views/discover_more_entry.php' , 'interests,page_ids'),
			( NULL , 'modules/discover_interests/views/discover_page_detail.php' , 'link_disable,page_info[0][''img''],page_info[0][''page_name''],page_info[0][''uri_name''],page_info[0][''page_id''],page_info[0][''type''],page_users'),
			( NULL , 'modules/graph/views/interests_graph.php' , 'config,sizes,tree_str'),
			( NULL , 'modules/graph/views/graphy.php' , 'config,sizes,tree_str,ipb'),
			( NULL , 'modules/connection/views/requests.php' , 'requests'),
			( NULL , 'modules/user_location/views/links_update.php' , 'links'),
			( NULL , 'modules/user_location/views/place_detail.php' , 'query->num_rows,query->result'),
			( NULL , 'modules/user_location/views/place_update.php' , 'query->result'),
			( NULL , 'modules/comment/views/up_new_entry.php' , 'up_data'),
			( NULL , 'modules/comment/views/comment.php' , 'comment->comment_id,comment->user_id_from,newsfeed_id,newsfeed->newsfeed_id,comment->user_from->avatar_small,comment->user_from->url'),
			( NULL , 'modules/comment/views/photo_comments.php' , 'photo_info[1][0][''data''],photo_info[0][0],photo_info[0][0][''user''],photo_info[0][0][''page''],photo_info[0],this,photo_info[0][0][''photo_id''],redirect_url,photo_info[0][0][''newsfeed_id''],photo_info[0][0][''page_id''],photo_info[0][0][''photo_caption'']'),
			( NULL , 'modules/comment/views/up_view.php' , 'news_array[''post_id''],newsfeed->up_count,newsfeed->activity->likes,newsfeed->activity->photo_id,newsfeed->activity->link_id,comment->comment_id'),
			( NULL , 'modules/comment/views/comments.php' , 'newsfeed->as_array,newsfeed->comment_count,newsfeed->activity->comments,newsfeed,newsfeed->activity->get,page_info[0][''uri_name''],my_data[''uri_name''],newsfeed->activity->photo_id,type,newsfeed->activity->page_id_to,newsfeed->newsfeed_id,loop_id,newsfeed->type,newsfeed->activity->link_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_limited_tile_list.php' , 'newsfeeds,view,category_type,topic_id'),
			( NULL , 'modules/newsfeed/views/popup_right.php' , 'newsfeed->newsfeed_id,view_type,newsfeed->type,newsfeed->activity->photo_id,newsfeed->activity->link_id,newsfeed->activity->likes,newsfeed->activity->get,newsfeed->activity->source,newsfeed->orig_user->url,newsfeed->orig_user->first_name,newsfeed->orig_user->last_name,newsfeed->orig_user_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_limited_montage.php' , 'newsfeed->type,newsfeed->link_type,newsfeed->activity_id,view,newsfeed->newsfeed_id,newsfeed->link_type_class,newsfeed,newsfeed->page_id_to,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,newsfeed->folder->url,newsfeed->folder->folder_name,newsfeed->folder->private,newsfeed->time,newsfeed->comment_count,profile_id,page_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_limited_tile.php' , 'newsfeed->type,newsfeed->link_type,newsfeed->activity_id,view,newsfeed->newsfeed_id,newsfeed->link_type_class,newsfeed,newsfeed->page_id_to,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,newsfeed->folder->url,newsfeed->folder->folder_name,newsfeed->folder->private,newsfeed->time,newsfeed->comment_count,profile_id,page_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_card.php' , 'newsfeed->type,newsfeed->link_type,newsfeed->activity_id,view,newsfeed->newsfeed_id,newsfeed->link_type_class,newsfeed,stage,newsfeed->folder,newsfeed->folder->private,profile_id,newsfeed->folder->url,newsfeed->collect_count,newsfeed->up_count,newsfeed->comment_count'),
			( NULL , 'modules/newsfeed/views/newsfeed_limited_montage_list.php' , 'newsfeeds,view,category_type,topic_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_tile.php' , 'newsfeed->type,newsfeed->link_type,newsfeed->activity_id,view,newsfeed->newsfeed_id,newsfeed->link_type_class,newsfeed,newsfeed->page_id_to,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,newsfeed->folder_id,newsfeed->folder->folder_name,newsfeed->folder->private,newsfeed->folder->url,newsfeed->user_from->url,newsfeed->user_from->first_name,newsfeed->user_from->last_name,newsfeed->time,newsfeed->collect_count,newsfeed->up_count,newsfeed->comment_count,profile_id,newsfeed->orig_user_id,newsfeed->user_id_from,newsfeed->orig_user->url,newsfeed->orig_user->full_name,newsfeed->folder->display_name'),
			( NULL , 'modules/newsfeed/views/newsfeed_tile_list.php' , 'cache_name,newsfeeds,view,last_timestamp,category_type,topic_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline_list.php' , 'newsfeeds,cache_name,view'),
			( NULL , 'modules/newsfeed/views/newsfeed_basic_list.php' , 'newsfeeds,view,category_type'),
			( NULL , 'modules/newsfeed/views/newsfeed_basic.php' , 'newsfeed->type,newsfeed->link_type,view,newsfeed->up_count,newsfeed->activity->likes,newsfeed->activity_id,newsfeed->newsfeed_id,newsfeed->folder->exclusive,newsfeed->activity->source,newsfeed->activity->link,newsfeed->activity->media,newsfeed,newsfeed->activity->content,newsfeed->activity->img_thumb,newsfeed->activity->img_width,newsfeed->activity->img_height,newsfeed->activity->text,newsfeed->folder,newsfeed->folder->get,newsfeed->time,newsfeed->activity->title,newsfeed->link_type_class,newsfeed->user_from->url,newsfeed->user_from->avatar_preview,newsfeed->user_from->full_name,newsfeed->activity->time,newsfeed->folder->url,newsfeed->folder->display_name,newsfeed->comment_count,newsfeed->activity->get,view_type,newsfeed->page_id_to,page_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_full_list.php' , 'view_type,newsfeeds'),
			( NULL , 'modules/newsfeed/views/source.php' , 'source,category_type'),
			( NULL , 'modules/newsfeed/views/activity.php' , 'view,activity->type,activity->url,activity->thumb,activity->user_id_to,activity->user_from,activity->user_from->url,activity->user_from->avatar_small,activity->user_id_from,activity->id,stage,activity->user_from->full_name,activity->user_from->first_name,activity->text,activity->time'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline_new_comment.php' , 'newsfeed->type,newsfeed->activity->photo_id,newsfeed->activity->link_id,recent_comment->user_from->avatar_small,recent_comment->user_from->url,recent_comment->user_from->first_name,recent_comment->user_from->last_name,recent_comment->comment,recent_comment->time,recent_comment,recent_comment->comment_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_item_full.php' , 'view_type,fvalue[''data''],fvalue[''type''],fvalue[''newsfeed_id''],fvalue[''page_id_to''],can_comment,fvalue[''relation''],ajax,news_aray[''page_id_to''],news_aray[''user_id_from''],page_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline.php' , 'newsfeed->up_count,newsfeed->activity->likes,view,newsfeed->type,newsfeed->link_type,newsfeed->activity->photo_id,newsfeed->activity->link_id,newsfeed->newsfeed_id,newsfeed->activity->link,newsfeed->user_from->id,newsfeed->user_from->url,newsfeed->user_from->avatar_preview,newsfeed,newsfeed->link_type_class,newsfeed->page_id_to,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,newsfeed->folder_id,newsfeed->folder->folder_name,newsfeed->folder->url,newsfeed->folder->display_name,newsfeed->user_from->first_name,newsfeed->user_from->last_name,newsfeed->activity->time,newsfeed->activity->img_thumb,newsfeed->activity->img_width,newsfeed->activity->img_height,newsfeed->activity->media,newsfeed->activity->content,like_data,newsfeed->activity->text,newsfeed->activity_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_home_interests.php' , 'can_comment,ajax,view'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline_edit.php' , 'newsfeed->newsfeed_id,newsfeed->type,newsfeed->activity->title,newsfeed->activity->caption'),
			( NULL , 'modules/newsfeed/views/newsfeed_link_popup.php' , 'fb_friends,fb_newsfeeds,view_type'),
			( NULL , 'modules/newsfeed/views/newsfeed.php' , 'view_type,page_id,post_type,profile_id,fvalue[''data'']'),
			( NULL , 'modules/newsfeed/views/newsfeed_tile_edit.php' , 'newsfeed->newsfeed_id,newsfeed->type,newsfeed->activity->title,newsfeed->activity->caption'),
			( NULL , 'modules/newsfeed/views/newsfeed_popup_edit.php' , 'newsfeed->newsfeed_id,newsfeed->activity->title,newsfeed->activity->caption,newsfeed->activity->text'),
			( NULL , 'modules/newsfeed/views/newsfeed_mag.php' , 'view_type,page_id,post_type,profile_id,fvalue[''data''],fvalue[''type''],fvalue[''newsfeed_id''],fvalue[''page_id_to''],entity_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline_new_list.php' , 'cache_name,newsfeeds,view'),
			( NULL , 'modules/newsfeed/views/newsfeed_card_list.php' , 'newsfeeds,view,category_type,topic_id'),
			( NULL , 'modules/newsfeed/views/activity_list.php' , 'ticker,profile_user->first_name,page'),
			( NULL , 'modules/newsfeed/views/view_modes_menu.php' , 'url'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline_new.php' , 'newsfeed->up_count,newsfeed->activity->likes,view,newsfeed->type,newsfeed->link_type,newsfeed->activity->photo_id,newsfeed->activity->link_id,newsfeed->newsfeed_id,newsfeed->folder->exclusive,newsfeed->activity->link,newsfeed->activity->source,newsfeed,newsfeed->activity->text,newsfeed->link_type_class,newsfeed->activity->img_width,newsfeed->activity->img_height,newsfeed->activity->img_thumb,newsfeed->activity->media,newsfeed->activity->content,newsfeed->activity_id,newsfeed->page_id_to,newsfeed->user_id_to,newsfeed->comment_count,newsfeed->user_from->id,newsfeed->user_from->url,newsfeed->user_from->avatar_small,newsfeed->user_from->full_name,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,newsfeed->folder_id,newsfeed->folder->folder_name,newsfeed->folder->private,newsfeed->folder->url,newsfeed->time,newsfeed->activity->caption,newsfeed->collect_count,newsfeed->activity->get,view_type,like_data_comm'),
			( NULL , 'modules/newsfeed/views/newsfeed_grid.php' , 'view_type,page_id,post_type,profile_id,fvalue[''data''],fvalue[''type''],fvalue[''newsfeed_id''],fvalue[''page_id_to''],entity_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_tile_new_comment.php' , 'recent_comment->user_from->avatar_small,newsfeed->type,newsfeed->activity->photo_id,newsfeed->activity->link_id,recent_comment->comment_id,newsfeed_id,recent_comment->user_from->url,recent_comment->user_from->first_name,recent_comment->user_from->last_name,recent_comment->comment'),
			( NULL , 'modules/newsfeed/views/newsfeed_edit_popup.php' , 'newsfeed->activity->caption'),
			( NULL , 'modules/google_image_search/views/getimages.php' , 'results,page_id,page'),
			( NULL , 'modules/google_image_search/views/gis_view.php' , 'page_name,page_id'),
			( NULL , 'modules/embed/views/collection_overview.php' , 'folder->url,folder->folder_id,folder->folder_name,folder->display_name,folder->private,folder->exclusive,folder->recent_newsfeeds,folder->drops,folder->total_hits'),
			( NULL , 'modules/fantoon-extensions/views/includes/header_embed.php' , 'base_url,title'),
			( NULL , 'modules/fantoon-extensions/views/includes/header_admin.php' , 'base_url,title'),
			( NULL , 'modules/fantoon-extensions/views/includes/sxsw_header.php' , 'base_url,title,hide_header'),
			( NULL , 'modules/fantoon-extensions/views/includes/header_lean.php' , 'base_url,title,hide_header'),
			( NULL , 'modules/fantoon-extensions/views/includes/header.php' , 'base_url,title,view,data'),
			( NULL , 'modules/fantoon-extensions/views/includes/footer.php' , 'hide_footer,hide_footer_links'),
			( NULL , 'modules/fantoon-extensions/views/includes/template.php' , 'main_content'),
			( NULL , 'modules/fantoon-extensions/views/includes/header_lean_centered.php' , 'base_url,title,hide_header'),
			( NULL , 'modules/admin/views/folders/select_folder_view.php' , 'folders'),
			( NULL , 'modules/admin/views/beanstalk_jobs.php' , 'limit,flots'),
			( NULL , 'modules/admin/views/list_sxsw_link_urls.php' , 'filters,list_fields,data,data->get_all,data->pagination->create_links'),
			( NULL , 'modules/admin/views/forms.php' , 'fields'),
			( NULL , 'modules/admin/views/stats.php' , 'method'),
			( NULL , 'modules/admin/views/filters.php' , 'filters'),
			( NULL , 'modules/admin/views/alpha_user.php' , 'filters,list_fields,data,list_actions'),
			( NULL , 'modules/admin/views/users/subscription_view.php' , 'filters,list_fields,items'),
			( NULL , 'modules/admin/views/users/list.php' , 'filters,list_fields,order,data,data->get_all,list_actions,data->pagination->create_links'),
			( NULL , 'modules/admin/views/dashboard.php' , 'data[''fb''],data[''tw''],data[''shared_links''],data[''folders_count''],data[''private_count''],data[''public_count''],data[''image_count''],data[''clip_count''],data[''screenshot_count''],data[''video_count''],data[''text_count'']'),
			( NULL , 'modules/admin/views/links/sources.php' , 'sources'),
			( NULL , 'modules/admin/views/stats/links.php' , 'types,sources'),
			( NULL , 'modules/admin/views/stats/users.php' , 'gender,linked'),
			( NULL , 'modules/admin/views/stats/sources.php' , 'keywords,landing_pages'),
			( NULL , 'modules/admin/views/stats/content.php' , 'page_views'),
			( NULL , 'modules/admin/views/stats/index.php' , 'page'),
			( NULL , 'modules/admin/views/form.php' , 'form_fields,list_fields,data,edit_actions,data'),
			( NULL , 'modules/admin/views/list.php' , 'filters,forms,filter_tabs,list_collection_actions,list_fields,order,foreign_fields,data,data->get_all,list_actions,data->pagination->create_links'),
			( NULL , 'modules/signup/views/twitter_logged.php' , 'user_info'),
			( NULL , 'modules/signup/views/register.php' , 'step,from,skip_registration,user_id,gender,dob_m,dob_d,dob_y,first_name,last_name,email_address,password,genders,months,days,years'),
			( NULL , 'modules/signup/views/hometest.php' , 'e'),
			( NULL , 'modules/signup/views/fandrop_aftersignup.php' , 'email_count'),
			( NULL , 'modules/signup/views/share_on_fb.php' , 'head_content,folder_url'),
			( NULL , 'modules/signup/views/email_form.php' , 'user_id'),
			( NULL , 'modules/signup/views/grabbed_info_basic.php' , 'fb_friends,power_users,fb_newsfeeds'),
			( NULL , 'modules/signup/views/category.php' , 'topics'),
			( NULL , 'modules/signup/views/register_form.php' , 'beta_id,fb_id,twitter_id,user_id,username,email_address,first_name,last_name,password'),
			( NULL , 'modules/signup/views/create_collections.php' , 'collections'),
			( NULL , 'modules/signup/views/add_user_info.php' , 'user_id'),
			( NULL , 'modules/signup/views/twitter_form.php' , 'beta_id,fb_id,twitter_id,user_id,first_name,last_name,username,email_address'),
			( NULL , 'modules/signup/views/request_invite.php' , 'signinUrl'),
			( NULL , 'modules/signup/views/more_info.php' , 'hide_twitter,hide_fb,fb_pages,twitter_id,twitter_pages,twitter_friends'),
			( NULL , 'modules/signup/views/grabbed_info.php' , 'collections,friends,power_users,links'),
			( NULL , 'modules/signup/views/basic_info.php' , 'username,beta_id,fb_id,twitter_id,loginUrl,user_id,first_name,last_name,email_address,password'),
			( NULL , 'modules/signup/views/fandrop_signup.php' , 'error_msg'),
			( NULL , 'modules/tools/views/fetch_link.php' , 'host,path'),
			( NULL , 'modules/tools/views/fetch.php' , 'rel,base,rel[0],host,path,pattern,content,match,match[1],key2,val2'),
			( NULL , 'modules/footer/views/about.php' , 'stage'),
			( NULL , 'modules/forget_password/views/resetpassword_view.php' , 'id,error_msg'),
			( NULL , 'modules/message/views/msg_inbox_entry.php' , 'message_thread[0],receiver,receiver[count'),
			( NULL , 'modules/message/views/recipients.php' , 'recipients'),
			( NULL , 'modules/message/views/msg_inbox.php' , 'title_info,msg_reply_id,msg_class,msg_body'),
			( NULL , 'modules/message/views/msg_thread_entry.php' , 'message_thread[0],thread_id'),
			( NULL , 'modules/message/views/msg_thread.php' , 'full_name,message_thread,to_user_id,user'),
			( NULL , 'modules/profile/views/profile_types.php' , 'profile_id,category_type'),
			( NULL , 'modules/profile/views/view_interests.php' , 'profile_user->id,your_interests,my_interests,page_ids'),
			( NULL , 'modules/profile/views/profile_top.php' , 'profile_user->url,profile_user->full_name,profile_user->badge->img,profile_user->badge->name,profile_user->id,check_friends,profile_user->user_stats[0]->collections,profile_user->user_stats[0]->total_drops,profile_user->drops_url,profile_user->user_stats[0]->likes,profile_user->likes_url,profile_user->user_stats[0]->mention,profile_user->mentions_url,profile_user->user_stats[0]->comments,profile_user->comments_url,profile_user->library_url,profile_user->images_url,profile_user->user_stats[0]->image,profile_user->clips_url,profile_user->user_stats[0]->clip,profile_user->user_stats[0]->screenshot,profile_user->videos_url,profile_user->user_stats[0]->video,profile_user->texts_url,profile_user->user_stats[0]->text,loginUrl'),
			( NULL , 'modules/profile/views/view_more_interests.php' , 'your_interests,my_interests,value,value->user->avatar_badge,value->user->id,value->user->gender,value->user->first_name,value->user->last_name,value->user->uri_name,value->user->url,page_ids'),
			( NULL , 'modules/profile/views/edit_personal_info.php' , 'month,day,b_years,year,m_gender,f_gender,info[0][''about''],quotes[0][''quotes''],info[0][''color_id''],contact[0][''email''],contact[0][''im''],contact[0][''phone''],contact[0][''address''],schools,data,years,add_info_groups[''color'']'),
			( NULL , 'modules/profile/views/profile_main.php' , 'include_file,profile_id,peopleshouldknow'),
			( NULL , 'modules/profile/views/profile.php' , 'inner_view,profile_user->id,stage,profile_user->avatar_thumb,profile_user->url,collection_dropdown,profile_user->drops_url,profile_user->likes_url,profile_user->uri_name,profile_user->first_name,isFollowingFollowerPage,loop_tabs,peopleshouldknow'),
			( NULL , 'modules/profile/views/connections_list.php' , 'your_connection_ids'),
			( NULL , 'modules/profile/views/account.php' , 'first_name,last_name,user->uri_name,loginUrl,email_settings->message,email_settings->comment,email_settings->up_link,email_settings->up_comment,email_settings->connection,email_settings->follow_folder,email_settings->collaboration,email_settings->newsletter,status'),
			( NULL , 'modules/profile/views/user_topics.php' , 'topics'),
			( NULL , 'modules/profile/views/gmail.php' , 'res,results'),
			( NULL , 'modules/profile/views/landing_page/landing_page_new.php' , 'topics,topic_uri_name,topic_id,drop_type'),
			( NULL , 'modules/profile/views/landing_page/landing_page_montage.php' , 'topics,topic_uri_name,topic_id,drop_type,popular_users'),
			( NULL , 'modules/profile/views/landing_page/landing_page.php' , 'topics,topic_uri_name,topic_id,drop_type,popular_users'),
			( NULL , 'modules/profile/views/user_info.php' , 'b_year,b_month,b_day,schools,profile_user->id,real_id,query->num_rows,query->result,link_query'),
			( NULL , 'modules/profile/views/profile_drops.php' , 'profile_uri,profile_id,category_type'),
			( NULL , 'modules/profile/views/profile_right.php' , 'profile_user->avatar_thumb,profile_user->id,profile_user->following,profile_user->follower'),
			( NULL , 'modules/profile/views/my_interests_edit.php' , 'vibe_question,vibe_info,questions,share_list,all_interests'),
			( NULL , 'modules/profile/views/edit_picture.php' , 'user->avatar_thumb'),
			( NULL , 'modules/profile/views/yahoo_email.php' , 'res,results'),
			( NULL , 'modules/profile/views/fb_friends_list.php' , 'results'),
			( NULL , 'modules/profile/views/friends_from_invite.php' , 'friends,following_ids'),
			( NULL , 'modules/profile/views/new_school_entry.php' , 'schools,years'),
			( NULL , 'modules/link/views/bar.php' , 'url,interests,folders'),
			( NULL , 'modules/facebook_app/views/timeline_app.php' , 'exc,e'),
			( NULL , 'modules/help/views/walkthrough.php' , 'stage'),
			( NULL , 'modules/folder/views/create_collection_popup.php' , 'default_topics,followings,button'),
			( NULL , 'modules/folder/views/folders.php' , 'profile_id,folders'),
			( NULL , 'modules/folder/views/folder_more_newsfeed.php' , 'view_type,folder_data,category_type'),
			( NULL , 'modules/folder/views/folder_list.php' , 'folders,profile_id,offset'),
			( NULL , 'modules/folder/views/folder_follow_button.php' , 'folder_id'),
			( NULL , 'modules/folder/views/folder_main.php' , 'profile_id,folders_dropdown,folders,category_type'),
			( NULL , 'modules/folder/views/folder_new_entry.php' , 'folder_info->folder_id,folder_info->folder_uri,folder_info->folder_name,folder_info->private,user_url_name'),
			( NULL , 'modules/folder/views/folder.php' , 'stage,folder_info->folder_id,folder_info->url,folder_info->private,folder_info->user_id,folder_info->get,folder_info->folder_name,folder_info->exclusive,collaborators,folder_info->topic_folders,profile_id'),
			( NULL , 'modules/folder/views/collect.php' , 'folders_dropdown'),
			( NULL , 'modules/folder/views/folder_following_button.php' , 'folder_id'),
			( NULL , 'modules/folder/views/profile_collection.php' , 'profile_id,folders_dropdown'),
			( NULL , 'modules/folder/views/folder_top.php' , 'folder_info->folder_name,folder_info->user->avatar_preview,folder_info->user->url,profile_user->full_name,profile_id,check_friends,profile_user->following,profile_user->follower,folder_info->drops,hits'),
			( NULL , 'modules/notification/views/notifications.php' , 'notifications'),
			( NULL , 'modules/notification/views/notifications_groups.php' , 'grouped_notifications'),
			( NULL , 'modules/notification/views/notifications_list.php' , 'grouped_notifications'),
			( NULL , 'modules/bookmarklet/views/popup.php' , 'url,page_id,folders,value'),
			( NULL , 'modules/bookmarklet/views/bar.php' , 'folders,recent,interests'),
			( NULL , 'modules/bookmarklet/views/snapshot.php' , 'item->activity->trimmed_left,item->activity->trimmed_top,content'),
			( NULL , 'modules/bookmarklet/views/login.php' , 'message'),
			( NULL , 'modules/bookmarklet/views/success.php' , 'newsfeed->newsfeed_id,newsfeed->folder->url,newsfeed->folder->folder_name,newsfeed->url'),
			( NULL , 'modules/bookmarklet/views/edit_post.php' , 'feed->activity->link_id,feed->activity->title,feed->link_type,feed->activity->thumb,feed->activity->content,folders,feed->folder_id'),
			( NULL , 'modules/bookmarklet/views/embed_popup.php' , 'folders')");

	}

	public function down()
	{
	}
}
