<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_Add_content_to_undefined_var_table extends CI_Migration {

	public function up()
	{
		mysql_query("INSERT INTO  `fantoon_ci`.`undefined_var` ( `id` , `view_page` , `variable`) VALUES
			( NULL , 'views/includes/footer_external.php', ''),
			( NULL , 'views/admin/alpha_users.php', ''),
			( NULL , 'views/admin/transfer.php', ''),
			( NULL , 'views/admin/admin.php', ''),
			( NULL , 'views/home/walkthrough.php', ''),
			( NULL , 'views/landing_page/landing_page_top.php', ''),
			( NULL , 'views/landing_page/landing_page_top_new.php', ''),
			( NULL , 'views/privacy/privacy.php', ''),
			( NULL , 'views/index.php', ''),
			( NULL , 'views/chat/chat.php', ''),
			( NULL , 'views/email_templates/invite_friends_template.php', ''),
			( NULL , 'views/email_templates/sxsw_invite.php', ''),
			( NULL , 'views/email_templates/newsletter_template.php', ''),
			( NULL , 'views/email_templates/collaboration_newsfeed_template.php', ''),
			( NULL , 'views/email_templates/up_template.php', ''),
			( NULL , 'views/email_templates/email_footer_unsubscribe.php', ''),
			( NULL , 'views/email_templates/signup_thanks_template.php', ''),
			( NULL , 'views/email_templates/common_template.php', ''),
			( NULL , 'views/email_templates/reply_template.php', ''),
			( NULL , 'views/email_templates/collaborator_email_template.php', ''),
			( NULL , 'views/email_templates/follow_list_template.php', ''),
			( NULL , 'views/email_templates/temp_newsletter.php', ''),
			( NULL , 'views/email_templates/resetpassword_template.php', ''),
			( NULL , 'views/email_templates/comment_template.php', ''),
			( NULL , 'views/email_templates/alpha_invite_template.php', ''),
			( NULL , 'views/email_templates/follow_folder_template.php', ''),
			( NULL , 'views/email_templates/welcome_template.php', ''),
			( NULL , 'views/email_templates/email_header.php', ''),
			( NULL , 'views/email_templates/collaborator_template.php', ''),
			( NULL , 'views/email_templates/connection_template.php', ''),
			( NULL , 'views/email_templates/email_header_fancy.php', ''),
			( NULL , 'views/email_templates/message_template.php', ''),
			( NULL , 'views/email_templates/email_footer.php', ''),
			( NULL , 'views/email_templates/mention_template.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_get_link_postbox.php', ''),
			( NULL , 'modules/sxsw/views/twitter_logged_in.php', ''),
			( NULL , 'modules/sxsw/views/up_template.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_post_login.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_email_3.php', ''),
			( NULL , 'modules/sxsw/views/comment_template.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_submit_link_popup.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_post_notification.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_email_1.php', ''),
			( NULL , 'modules/sxsw/views/sxsw_email_2.php', ''),
			( NULL , 'modules/sxsw/views/unsubscribe.php', ''),
			( NULL , 'modules/user_location/views/links_details.php', ''),
			( NULL , 'modules/newsfeed/views/newsfeed_delete_popup.php', ''),
			( NULL , 'modules/embed/views/collection_no_exist.php', ''),
			( NULL , 'modules/admin/views/layout.php', ''),
			( NULL , 'modules/admin/views/alpha_invite_template.php', ''),
			( NULL , 'modules/admin/views/users/settings_view.php', ''),
			( NULL , 'modules/admin/views/users/create_user.php', ''),
			( NULL , 'modules/admin/views/auth/index.php', ''),
			( NULL , 'modules/admin/views/home.php', ''),
			( NULL , 'modules/admin/views/stats/general.php', ''),
			( NULL , 'modules/signup/views/twitter_logged_in.php', ''),
			( NULL , 'modules/signup/views/signup_error.php', ''),
			( NULL , 'modules/signup/views/login.php', ''),
			( NULL , 'modules/tools/views/test_url.php', ''),
			( NULL , 'modules/footer/views/about_team_spec.php', ''),
			( NULL , 'modules/footer/views/contact_us.php', ''),
			( NULL , 'modules/footer/views/successful_contact.php', ''),
			( NULL , 'modules/footer/views/about_terms.php', ''),
			( NULL , 'modules/footer/views/about_team.php', ''),
			( NULL , 'modules/footer/views/about_main.php', ''),
			( NULL , 'modules/footer/views/about_privacy.php', ''),
			( NULL , 'modules/footer/views/about_contactus.php', ''),
			( NULL , 'modules/footer/views/about_copyright.php', ''),
			( NULL , 'modules/footer/views/contact_form.php', ''),
			( NULL , 'modules/footer/views/about_jobs.php', ''),
			( NULL , 'modules/forget_password/views/forgetpassword_step2.php', ''),
			( NULL , 'modules/profile/views/twitter_connected.php', ''),
			( NULL , 'modules/profile/views/no_profile.php', ''),
			( NULL , 'modules/profile/views/invite_popup.php', ''),
			( NULL , 'modules/profile/views/yahoo_after.php', ''),
			( NULL , 'modules/profile/views/gmail.auth.php', ''),
			( NULL , 'modules/profile/views/de_profile.php', ''),
			( NULL , 'modules/profile/views/gmail_after.php', ''),
			( NULL , 'modules/profile/views/unsubscribe.php', ''),
			( NULL , 'modules/link/views/popup.php', ''),
			( NULL , 'modules/api/views/test_page.php', ''),
			( NULL , 'modules/help/views/walkthrough_discovery.php', ''),
			( NULL , 'modules/help/views/walkthrough_home.php', ''),
			( NULL , 'modules/help/views/walkthrough_profile.php', ''),
			( NULL , 'modules/help/views/walkthrough_interest.php', ''),
			( NULL , 'modules/help/views/walkthrough_start.php', ''),
			( NULL , 'modules/folder/views/delete_collection_popup.php', ''),
			( NULL , 'modules/folder/views/folder_embed_popup.php', ''),
			( NULL , 'modules/migrate/views/actions_view.php', ''),
			( NULL , 'modules/bookmarklet/views/info_dialog.php', ''),
			( NULL , 'modules/bookmarklet/views/share_drop_on_fb.php', ''),
			( NULL , 'modules/bookmarklet/views/walkthrough.php', ''),
			( NULL , 'views/list/list_newsfeed.php' , 'stage,num_interests,page_array,fvalue[''data''],list_info[0][''list_name''],check_list_user,list_info[0][''list_id''],fvalue'),
			( NULL , 'views/custom_tab/custom_tab.php' , 'owner_priv,admin_priv,tab[0][''activated''],tab,tab_v[''activated''],tab_v[''tab_name''],tab_content,content_v[''type''],content_v[''content''],content_v[''component_id'']'),
			( NULL , 'views/badge/badge.php' , 'type,user->id,user->user_stats[0]->total_drops,user->user_stats[0]->likes,user->url,user->avatar_badge,user->first_name,user->last_name,collections_number,user->drops_url,user->likes_url,check_friends,page_info[''page_id''],page_info[''thumbnail''],page_info[''interest_id''],stage,page_info[''uri_name''],link_disable,in,owner_priv,admin_priv,page_info[''page_name''],page_description,page_info[''hits''],page_users,value[''uri_name''],value[''user_id''],value[''thumbnail''],value[''gender''],value[''first_name''],value[''last_name'']'),
			( NULL , 'views/photos/albums.php' , 'profile_id,my_data[''first_name''],my_data[''last_name''],page_id,albums,value[''album_id''],id,value[''thumb''],value[''album_name''],value[''photo_count''],myphotos_count,myphotos_thumb'),
			( NULL , 'views/photos/show_photo.php' , 'album_info[0][''album_name''],album_photos,photos_array,value[''album_name''],value[''photo_name''],value[''photo_caption''],value[''photo_id''],value[''loop_id''],value[''album_id''],photo_info[0][0][''photo_name''],photo_info[0][0][''photo_caption'']'),
			( NULL , 'views/photos/photos.php' , 'ajax,album[0][''album_name''],photos,value[''photo_id''],pid,value[''user_id''],value[''page_id''],value[''loop_id''],value[''album_id''],value[''photo_name''],value[''photo_caption'']'),
			( NULL , 'views/includes/header_embed.php' , 'base_url,title'),
			( NULL , 'views/includes/header_admin.php' , 'base_url,title'),
			( NULL , 'views/includes/sxsw_header.php' , 'base_url,title,first_visit,disp_postbox,hide_header'),
			( NULL , 'views/includes/header_lean.php' , 'base_url,title,css_filename_data[1],first_visit,hide_header,include_login'),
			( NULL , 'views/includes/header.php' , 'base_url,head_content,title,css_filename_data[1],first_visit,hide_header,view,main_content,data,disable_landing_top'),
			( NULL , 'views/includes/header_external.php' , 'css_filename_data[1],no_id'),
			( NULL , 'views/includes/footer.php' , 'hide_footer,hide_footer_links'),
			( NULL , 'views/includes/template.php' , 'header,main_content,footer'),
			( NULL , 'views/includes/header_lean_centered.php' , 'base_url,title,css_filename_data[1],first_visit,hide_header'),
			( NULL , 'views/admin/admin_questions.php' , 'questions,v[''q_id''],v[''title''],v[''question''],v[''display'']'),
			( NULL , 'views/admin/admin_aliases.php' , 'aliases'),
			( NULL , 'views/admin/admin_pages.php' , 'pages'),
			( NULL , 'views/admin/edit_question.php' , 'question,v[''q_id''],v[''title''],v[''question'']'),
			( NULL , 'views/event/events.php' , 'display_type,view_type,events,value[''event_id''],eid,value[''data''],value[''start_time''],value[''end_time''],value[''privacy''],owner_priv,admin_priv,value[''more''],item[''user_id''],item[''uri_name''],item[''first_name''],item[''last_name''],value[''location''],value[''address''],value[''city''],value[''zip_code''],value[''description''],value[''attendees''],v,v[''event_id''],invitees[\$v[''response'']],v[''user_link''],value[''img''],value[''page_id''],show_comments,value,value[''event_name''],response[\$value[''event_id'']],page_users,value[''user_id''],value[''uri_name''],value[''first_name''],value[''last_name'']'),
			( NULL , 'views/event/edit_event.php' , 'event,value[''event_name''],value[''start_time''],value[''end_time''],value[''location''],value[''address''],value[''city''],value[''zip_code''],value[''description''],value[''privacy''],value[''more''],item[''user_id''],item[''uri_name''],item[''first_name''],item[''last_name''],value[''attendees''],value[''img''],value[''page_id'']'),
			( NULL , 'views/home/home_update_friends.php' , 'newsfeeds,view_type,page_id,post_type,profile_id,fvalue'),
			( NULL , 'views/home/newsfeed_layout/magazine.php' , 'mag_lay->rend_social,most_recent_timestamp'),
			( NULL , 'views/home/newsfeed_layout/magazine1.php' , 'items'),
			( NULL , 'views/home/home_update_interest.php' , 'view,view_layout,newsfeeds,mag_lay->rend_arr'),
			( NULL , 'views/home/home_main.php' , 'category_type,topic->topic_name,topic,topics,topic_uri_name,topic->uri_name,topic->url,drop_type,ticker,activity,my_pages,item[''page_id''],item[''page_name''],connection_list,item,item[''uid''],item[''uri_name''],item[''first_name''],item[''last_name''],my_loops,loops'),
			( NULL , 'views/home/home_update_activity.php' , 'ticker,activity,view_type'),
			( NULL , 'views/home/home.php' , 'include_file'),
			( NULL , 'views/search/search_index_results.php' , 'welcome_msg,following_user_results,v_user[''id''],v_user[''uri_name''],v_user[''first_name''],v_user[''last_name''],follower_user_results,v_user,user_results,in_page_results,v_page[''avatar''],v_page[''interest_id''],v_page[''page_id''],v_page[''alias_name''],v_page[''page_name''],v_page[''redirect_url''],v_page[''official_url''],v_page[''uri_name''],page_results,v_page'),
			( NULL , 'views/search/search_drops_results.php' , 'newsfeeds,loadmore,category_type,back_url,stage,profile_id,folder_info,folder_info->folder_id'),
			( NULL , 'views/search/search_results.php' , 'search_category,results_count,inner_view'),
			( NULL , 'views/search/search_topics_results.php' , 'results,topic->url,topic->topic_name'),
			( NULL , 'views/search/search_collections_results.php' , 'autoscroll,results,fv->folder_id,fv->user_id,fv->folder_name,fv->url,fv->display_name,fv->private,fv->recent_newsfeeds,item->type,item->link_type,item->text,item->title,item->bigimg,item->img,fv->user->url,fv->user->avatar_small,fv->user->first_name,fv->user->last_name,fv->folder_contributors[0]->user_id,fv->drops,fv->hits,fv->editable,fv->following,loadmore'),
			( NULL , 'views/landing_page/landing_page_old.php' , 'user_info[''fb_id''],user_info[''t_id'']'),
			( NULL , 'views/landing_page/landing_page_new.php' , 'topics,topic_uri_name,topic_id,drop_type'),
			( NULL , 'views/landing_page/landing_page_montage.php' , 'topics,topic_uri_name,topic_id,drop_type,popular_users'),
			( NULL , 'views/landing_page/landing_page.php' , 'topics,topic_uri_name,topic_id,drop_type,popular_users'),
			( NULL , 'views/loop/loops_view.php' , 'circle_element,s],avatar,s,friendname,circlename,circle_order,circlebox,c,c[''left''],c[''top''],friendbox,avatar[\$i],c[''cid'']'),
			( NULL , 'views/loop/edit_loop.php' , 'loop_id,loop_info[''loop_name''],my_connections,item[''uid''],item[''check''],item[''uri_name''],item[''first_name''],item[''last_name''],my_follow,item'),
			( NULL , 'views/loop/loop.php' , 'view_type,feeds_array,value[''type''],news_array[0],news_array[1]'),
			( NULL , 'views/error.php' , 'error,descripion'),
			( NULL , 'views/chat/main_page.php' , 'myname,selfonline,soundmute,havefriend,friendlistid,friendlist_name,user'),
			( NULL , 'views/pr/pr.php' , 'owner_priv,admin_priv,pr_lock,pr_error,prs,value[''data''],value[''source_link''],value[''source_title''],value[''uri_name''],value[''user_id''],value[''first_name''],value[''last_name''],value[''source_date''],value[''page_id''],value[''newsfeed_id''],value[''pr_id''],like_value[''user_id''],view_type,like_value,like_value[''link''],cv[''link''],cv[''ctime''],cv[''user_id_from''],cv[''user_id_to''],cv[''comment_id''],cv[''comment''],cv[''page_id_from''],cv[''likes''],l_value[''link'']'),
			( NULL , 'views/recommendations/recommender.php' , 'page1Id,page2Id,pageSimResult,user1Id,user2Id,userSimResult,processTime,userId,recommendations,methodName,value'),
			( NULL , 'views/recommendations/gen_similarity_finish.php' , 'title,content'),
			( NULL , 'modules/topics/views/topic_more_interests.php' , 'pages,value[''page_id''],value[''uri_name''],value[''thumbnail''],value[''interest_id''],value[''page_name''],loaded_pages'),
			( NULL , 'modules/topics/views/topic_new_entry.php' , 'path,value,v[''topic_id''],v[''topic_name''],node_id,node_name,current_id'),
			( NULL , 'modules/topics/views/topic_feeds.php' , 'topic_id,page_id,topic_name,stage,source,include_file,main_pic,topic_pages,hits,value[''thumbnail''],value[''interest_id''],value[''official_url''],value[''uri_name''],value[''page_id'']'),
			( NULL , 'modules/topics/views/topic_page.php' , 'topic_name,user_id,topic_aliases,merge_topics,parent_id,v[''topic_id''],v[''topic_name''],child_id,v,path,value'),
			( NULL , 'modules/topics/views/topic_newsfeed.php' , 'feeds_array'),
			( NULL , 'modules/topics/views/topic_delete.php' , 'path,value,v[''topic_id''],v[''topic_name'']'),
			( NULL , 'modules/topics/views/topic_new_alias.php' , 'alias_name,topic_id,alias_id'),
			( NULL , 'modules/topics/views/topic_organize.php' , 'topic_name,user_id,topic_aliases,merge_topics,parent_id,v[''topic_id''],v[''topic_name''],child_id,v,path,value'),
			( NULL , 'modules/topics/views/topic_interests.php' , 'pages,value[''page_id''],value[''uri_name''],value[''thumbnail''],value[''interest_id''],value[''page_name''],loaded_pages'),
			( NULL , 'modules/topics/views/edit_picture.php' , 'topic_id,topic_name'),
			( NULL , 'modules/topics/views/topic_info.php' , 'topic_name,pages,v[''thumbnail''],v[''interest_id''],v[''uri_name''],v[''page_id''],v[''page_name''],config,sizes,tree_str'),
			( NULL , 'modules/interests/views/page_new_feature_edit.php' , 'page_info,pv[''id''],pv[''thumbnail''],pv[''interest_id''],pv[''official_url''],pv[''uri_name''],page_id,pv[''page_name'']'),
			( NULL , 'modules/interests/views/page_info.php' , 'type_form[0],info[''address''],info[''city''],info[''zip''],info[''phone''],info[''email''],info[''founded''],info[''about''],info[''description''],info[''website''],info[''product''],info[''hour''],info[''food_served''],info[''specialty''],info[''food''],info[''interest''],info[''gender''],info[''birthday''],info[''biograph''],info[''current_location''],info,info[''release_date''],info[''members''],info[''record_label''],info[''manager_name''],info[''booking_agent''],info[''press_contact''],info[''influence''],info[''hometown''],info[''award''],info[''label_record''],info[''member''],info[''schedule''],info[''genre''],info[''written_by''],info[''isbn''],info[''directed_by''],info[''starring'']'),
			( NULL , 'modules/interests/views/page_sidebar.php' , 'main_pic,mod_priv,editor_priv'),
			( NULL , 'modules/interests/views/page_info_common.php' , 'info[''interest''],info[''gender''],info[''birthday''],info[''hometown''],info[''biograph''],info[''phone''],info[''email''],info[''current_location''],info[''about''],info[''description''],info[''website''],info[''college''],info[''manager_name''],info[''booking_agent''],info[''press_contact''],info[''award'']'),
			( NULL , 'modules/interests/views/fans_section_img.php' , 'value[''thumbnail''],value[''gender''],value[''uri_name''],value[''user_id''],value[''first_name''],value[''last_name''],your_connection_ids'),
			( NULL , 'modules/interests/views/feature_page_edit.php' , 'page_info[0][''page_name''],page_info[0][''uri_name''],page_info[0][''page_id''],page_info[0][''owner_id''],admin_priv,editor_priv,page_id,featured_dropdown,feature_pages,item[''thumbnail''],item[''interest_id''],item[''official_url''],item[''uri_name''],item[''page_id''],item[''page_name'']'),
			( NULL , 'modules/interests/views/page_topics.php' , 'topic_list,value,page_id'),
			( NULL , 'modules/interests/views/page.php' , 'first_visit,page_id,page_info[0][''topic_lock''],page_info[0][''uri_name''],page_info[0][''page_name''],owner_priv,admin_priv,mod_priv,editor_priv,in,fans,page_edit_mode,uri_name,record,record[\$i][''user_id''],include_file,page->avatar,page_info[0][''hits''],myself[''thumbnail''],myself[''gender''],myself[''uri_name''],myself[''id''],record_in_follower,value[''thumbnail''],value[''gender''],value[''uri_name''],value[''user_id''],value[''role''],record_in_following,value,share_list,value[''first_name''],value[''last_name''],value[''id''],record_out'),
			( NULL , 'modules/interests/views/register_page.php' , 'error'),
			( NULL , 'modules/interests/views/page_fans.php' , 'in,follower,value,following,fans,record_in_follower,record_in_following,value[''thumbnail''],value[''gender''],value[''uri_name''],value[''user_id''],value[''first_name''],value[''last_name''],your_connection_ids'),
			( NULL , 'modules/interests/views/feature_interests.php' , 'feature_pages,item[''thumbnail''],item[''interest_id''],item[''official_url''],item[''uri_name''],item[''page_id''],item[''page_name'']'),
			( NULL , 'modules/interests/views/community_edit_common.php' , 'item[''uri_name''],item[''user_id''],item[''thumbnail''],item[''gender''],item[''first_name''],item[''last_name''],owner_priv,page_id,admin_priv,item[''role''],mod_priv'),
			( NULL , 'modules/interests/views/edit_picture.php' , 'page->avatar,page->page_id,page->page_name'),
			( NULL , 'modules/interests/views/community_edit.php' , 'page_info[0][''page_name''],page_info[0][''uri_name''],page_info[0][''page_id''],owner,item[''uri_name''],item[''user_id''],item[''thumbnail''],item[''gender''],item[''first_name''],item[''last_name''],owner_priv,admin_priv,item[''role''],page_id,mod_priv,admin,item,mod,fan'),
			( NULL , 'modules/interests/views/page_wall.php' , 'page_info[0][''official_url''],page_info[0][''uri_name''],page_info[0][''page_id''],thread_info[''thread_name''],page_info[0][''page_name''],threds,threads,v[''t_id''],page_id,v[''thread_name''],owner_priv,admin_priv,v[''last''][''post''],v[''last''][''time''],v[''last''][''first_name''],v[''last''][''last_name''],v[''replies''],v[''views''],newsfeeds,feeds_array'),
			( NULL , 'modules/interests/views/page_new_feature.php' , 'page_info,pv[''id''],pv[''thumbnail''],pv[''interest_id''],pv[''official_url''],pv[''uri_name'']'),
			( NULL , 'modules/interests/views/edit_page_info.php' , 'page_info[0][''page_name''],page_info[0][''uri_name''],page_info[0][''page_id''],official_upgrade,page_info[0][''cid''],categories_all,interest_categories,type_form[0][''interest_id''],type_form[0][''form''],info[0][''address''],info[0][''city''],info[0][''zip''],info[0][''phone''],info[0][''email''],info[0][''founded''],info[0][''about''],info[0][''description''],info[0][''website''],info[0][''product''],info[0][''hour''],info[0][''interest''],info[0][''gender''],info[0][''birthday''],info[0][''hometown''],info[0][''biograph''],info[0][''current_location''],info[0][''college''],info[0][''award''],info[0][''release_date''],info[0][''member''],info[0][''record_label''],info[0][''manager_name''],info[0][''booking_agent''],info[0][''press_contact''],info[0][''influence''],info[0][''label_record''],info[0][''schedule''],info[0][''genre''],info[0][''written_by''],info[0][''isbn''],info[0][''directed_by''],info[0][''starring''],page_id'),
			( NULL , 'modules/interests/views/page_wizard.php' , 'role,categories'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_tile.php' , 'view,item->sxsw_likes,item->id,item->like_count,item->link_url,item->uniqid,item->title,item->image,item->comment_count,item->sxsw_user->id,item->sxsw_user->thumbnail,item->sxsw_user->first_name,item->sxsw_user->last_name,item->category,item->time,item->get,l_value->user_id,item->sxsw_comments'),
			( NULL , 'modules/sxsw/views/sxsw_link_popup.php' , 'item->id,item->sxsw_likes,like_value->user_id,item->media,item->link_url,item->image,item->title,title,item->uniqid,item->sxsw_user->id,item->sxsw_user->thumbnail,item->sxsw_user->first_name,item->sxsw_user->last_name,item->time,item->comment_count,item->get,cv->sxsw_comment_likes,comm_like_value->user_id,cv->id,cv->user_id,cv->sxsw_user->id,cv->sxsw_user->thumbnail,cv->sxsw_user->first_name,cv->sxsw_user->last_name,cv->time,cv->comment'),
			( NULL , 'modules/sxsw/views/sxsw_up_view.php' , 'this,ci->session,for_comment,cv->sxsw_comment_likes,item->sxsw_likes,for_link,item->id,cv->id,like_count-1'),
			( NULL , 'modules/sxsw/views/sxsw_external_connect.php' , 'is_post,fb_id,twitter_id'),
			( NULL , 'modules/sxsw/views/sxsw_user.php' , 'twitter_id,fb_id,full_name,signup_url,user->id,link_type,user->thumbnail,user->first_name,user->last_name,link_count,comment_count,like_count,view_type,category,connected,uniqid,item->title'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_timeline.php' , 'item->sxsw_likes,like_value->user_id,item->link_url,f_count,view,item->id,item->sxsw_user->id,item->sxsw_user->thumbnail,item->sxsw_user->first_name,item->sxsw_user->last_name,item->time,item->category,item->uniqid,item->like_count,item->image,item->get,ccv,session->userdata,l_value->user_id,item->comment_count'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_tile_list.php' , 'links,category,user->id,link_type'),
			( NULL , 'modules/sxsw/views/sxsw_index.php' , 'twitter_id,fb_id,full_name,signup_url,view_type,category,connected,uniqid,item->title'),
			( NULL , 'modules/sxsw/views/sxsw_likes.php' , 'likes,lv,lv->sxsw_user'),
			( NULL , 'modules/sxsw/views/sxsw_all_comments.php' , 'item->sxsw_likes,like_value->user_id,item->sxsw_user->id,item->sxsw_user->thumbnail,item->sxsw_user->first_name,item->sxsw_user->last_name,item->time,item->comment_count,item->id,item->get,cv->sxsw_comment_likes,comm_like_value->user_id,cv->id,cv->user_id,cv->sxsw_user->id,cv->sxsw_user->thumbnail,cv->sxsw_user->first_name,cv->sxsw_user->last_name,cv->time,cv->comment'),
			( NULL , 'modules/sxsw/views/sxsw_post_link.php' , 'category_dropdown,links,photos'),
			( NULL , 'modules/sxsw/views/sxsw_fandrop_aftersignup.php' , 'email_count'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_timeline_newcomment.php' , 'comment->id,comment->sxsw_user->thumbnail,comment->user_id,comment->sxsw_user->id,comment->sxsw_user->first_name,comment->sxsw_user->last_name,comment->comment,comment->time,comment,comment->sxsw_comment_likes,session->userdata,l_value->user_id'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_tile_newcomment.php' , 'comment->id,comment->sxsw_user->id,comment->sxsw_user->thumbnail,comment->sxsw_user->first_name,comment->sxsw_user->last_name,comment->comment'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_full_newcomment.php' , 'comment->id,comment->user_id,comment->sxsw_user->id,comment->sxsw_user->thumbnail,comment->sxsw_user->first_name,comment->sxsw_user->last_name,comment->time,comment->comment,comment'),
			( NULL , 'modules/sxsw/views/sxsw_fandrop_signup.php' , 'error_msg'),
			( NULL , 'modules/sxsw/views/sxsw_newsfeed_timeline_list.php' , 'links,category,user->id,link_type'),
			( NULL , 'modules/list/views/list_edit.php' , 'list_info[0][''list_name''],list_info[0][''list_id''],list_info[0][''description''],list_info[0][''visibility'']'),
			( NULL , 'modules/list/views/show_lists.php' , 'my_lists,following_lists,profile_id,my_data[''first_name''],list_value[''list_name''],list_value[''follow''],list_value[''list_id''],list_value[''pages''],pv[''uri_name''],pv[''page_id''],pv[''thumbnail''],pv[''interest_id''],list_value,pv'),
			( NULL , 'modules/list/views/page_lists.php' , 'page_lists,following_lists,page_name[''page_name''],list_value[''list_name''],list_value[''list_maker_id''],list_value[''follow''],list_value[''list_id''],list_value[''pages''],pv[''uri_name''],pv[''page_id''],pv[''thumbnail''],pv[''interest_id''],profile_id'),
			( NULL , 'modules/list/views/list_view.php' , 'first_visit,friendname,avatar[\$i],c,circlebox,c[''cid''],circle_order,circlename,avatar,c[''left''],c[''top''],friendbox,circle_element,s'),
			( NULL , 'modules/list/views/list_newsfeed.php' , 'num_interests,page_array,fvalue[''data''],called_by,fvalue'),
			( NULL , 'modules/list/views/list.php' , 'my_pages,item[''page_id''],item[''page_name'']'),
			( NULL , 'modules/discover_interests/views/discover_interests.php' , 'stage,link_disabled,link_disable,my_interests,vvv,val,interest_categories,value,interest_count[\$value[''id'']],value[''id''],value[''type''],interests,v[''page_name''],v[''official_url''],v[''uri_name''],v[''page_id''],v[''basic_info''],v[''img''],page_ids'),
			( NULL , 'modules/discover_interests/views/discover_more_entry.php' , 'interests,v[''page_name''],v[''official_url''],v[''uri_name''],v[''page_id''],link_disable,v[''basic_info''],v[''img''],page_ids'),
			( NULL , 'modules/discover_interests/views/discover_page_detail.php' , 'link_disable,page_info[0][''img''],page_info[0][''page_name''],page_info[0][''uri_name''],page_info[0][''page_id''],page_info[0][''type''],page_users'),
			( NULL , 'modules/graph/views/interests_graph.php' , 'config,sizes,tree_str'),
			( NULL , 'modules/graph/views/graphy.php' , 'config,sizes,tree_str,ipb'),
			( NULL , 'modules/connection/views/requests.php' , 'requests,item[''thumbnail''],item[''gender''],item[''uri_name''],item[''initiator_id''],item[''first_name''],item[''last_name'']'),
			( NULL , 'modules/user_location/views/links_update.php' , 'query->num_rows,query->result'),
			( NULL , 'modules/user_location/views/place_detail.php' , 'query->num_rows,query->result'),
			( NULL , 'modules/user_location/views/place_update.php' , 'query->result'),
			( NULL , 'modules/comment/views/up_new_entry.php' , 'up_data,lv->user_from->user_stats[0]->total_drops,lv->user_from->user_stats[0]->likes,lv->user_from->user_stats[0]->collections,lv->user_id,lv->user_from->url,lv->user_from->avatar_small,lv->user_from->first_name,lv->user_from->last_name,lv->user_from->drops_url,lv->user_from->likes_url,lv->user_from->id,lv[''page_uri''],lv[''page_id''],lv[''page_thumbnail''],lv[''page_name'']'),
			( NULL , 'modules/comment/views/comment.php' , 'session->userdata[''id''],session,comment->comment_id,comment->user_id_from,owner_priv,admin_priv,editor_priv,newsfeed_id,newsfeed->newsfeed_id,comment->user_from->avatar_small,comment->user_from->url'),
			( NULL , 'modules/comment/views/photo_comments.php' , 'photo_info[1][0][''data''],photo_info[0][0],photo_info[0][0][''user''],photo_info[0][0][''page''],photo_info[0],pvalue[''user_id''],cv[''page_id_from''],cv[''thumbnail''],cv[''category_id''],this,photo_info[0][0][''photo_id''],redirect_url,photo_info[0][0][''newsfeed_id''],photo_info[0][0][''page_id''],photo_info[0][0][''photo_caption'']'),
			( NULL , 'modules/comment/views/up_view.php' , 'like_type,news_array[''likes''],news_array[''post_id''],newsfeed->up_count,newsfeed->activity->likes,newsfeed->activity->photo_id,newsfeed->activity->link_id,comment->likes,comment->comment_id,like->user_id,like,like->user_from->url,like->user_from->full_name'),
			( NULL , 'modules/comment/views/comments.php' , 'fvalue,item,item->as_array,newsfeed->as_array,fvalue[''data''],newsfeed->comment_count,newsfeed->activity->comments,comment->parent_id,comment->comment_id,comment,newsfeed,comments_record,this,newsfeed->activity->get,comment->page_id_from,fvalue[''type''],page_info[0][''uri_name''],my_data[''uri_name''],newsfeed->activity->photo_id,type,newsfeed->activity->page_id_to,newsfeed->newsfeed_id,loop_id,fvalue[''newsfeed_id''],newsfeed->type,newsfeed->activity->link_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_limited_tile_list.php' , 'newsfeeds,page_id,view,category_type,topic_id'),
			( NULL , 'modules/newsfeed/views/popup_right.php' , 'newsfeed->newsfeed_id,view_type,newsfeed->up_count,newsfeed->type,newsfeed->activity->photo_id,newsfeed->activity->link_id,newsfeed->activity->likes,like_count,like_limit,newsfeed->collect_count,newsfeed->activity->get,redrop_count,redrop_limit,newsfeed->activity->source,same_source_links,newsfeed->orig_user->url,newsfeed->orig_user->first_name,newsfeed->orig_user->last_name,newsfeed->orig_user_id,follow_orig_user,orig_user_newsfeeds'),
			( NULL , 'modules/newsfeed/views/newsfeed_limited_montage.php' , 'newsfeed->type,newsfeed->link_type,newsfeed->activity_id,view,newsfeed->newsfeed_id,newsfeed->link_type_class,can_edit,newsfeed,newsfeed->page_id_to,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,newsfeed->folder->url,newsfeed->folder->folder_name,newsfeed->folder->private,newsfeed->time,newsfeed->comment_count,profile_id,page_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_limited_tile.php' , 'newsfeed->type,newsfeed->link_type,newsfeed->activity_id,view,newsfeed->newsfeed_id,newsfeed->link_type_class,can_edit,newsfeed,newsfeed->page_id_to,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,newsfeed->folder->url,newsfeed->folder->folder_name,newsfeed->folder->private,newsfeed->time,newsfeed->comment_count,profile_id,page_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_card.php' , 'newsfeed->type,newsfeed->link_type,newsfeed->activity_id,view,newsfeed->newsfeed_id,newsfeed->link_type_class,can_edit,newsfeed,page_id,stage,newsfeed->folder,newsfeed->folder->private,profile_id,newsfeed->folder->folder_name,newsfeed->folder->url,newsfeed->collect_count,newsfeed->up_count,newsfeed->comment_count,owner_priv,admin_priv,editor_priv'),
			( NULL , 'modules/newsfeed/views/newsfeed_limited_montage_list.php' , 'newsfeeds,page_id,view,category_type,topic_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_tile.php' , 'newsfeed->type,newsfeed->link_type,newsfeed->activity_id,view,newsfeed->newsfeed_id,newsfeed->link_type_class,can_edit,newsfeed,newsfeed->page_id_to,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,newsfeed->folder_id,newsfeed->folder->folder_name,newsfeed->folder->private,newsfeed->folder->url,newsfeed->user_from->url,newsfeed->user_from->first_name,newsfeed->user_from->last_name,newsfeed->time,page_id,newsfeed->collect_count,newsfeed->up_count,newsfeed->comment_count,disable_in_folder,profile_id,newsfeed->orig_user_id,newsfeed->user_id_from,newsfeed->orig_user->url,newsfeed->orig_user->full_name,newsfeed->folder->display_name,owner_priv,admin_priv,editor_priv'),
			( NULL , 'modules/newsfeed/views/newsfeed_tile_list.php' , 'cache_name,newsfeeds,page_id,view,last_timestamp,category_type,topic_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline_list.php' , 'newsfeeds,cache_name,page_id,view'),
			( NULL , 'modules/newsfeed/views/newsfeed_basic_list.php' , 'cache_name,newsfeeds,page_id,view,category_type'),
			( NULL , 'modules/newsfeed/views/newsfeed_basic.php' , 'newsfeed->type,newsfeed->link_type,f_count,view,newsfeed->up_count,newsfeed->activity->likes,newsfeed->activity_id,newsfeed->newsfeed_id,newsfeed->activity->source,newsfeed->activity->link,newsfeed->activity->media,newsfeed,newsfeed->activity->content,newsfeed->activity->img_thumb,newsfeed->activity->img_width,newsfeed->activity->img_height,newsfeed->activity->text,newsfeed->folder,newsfeed->folder->get,newsfeed->time,newsfeed->activity->title,newsfeed->link_type_class,newsfeed->user_from->url,newsfeed->user_from->avatar_preview,newsfeed->user_from->full_name,newsfeed->activity->time,newsfeed->folder->url,newsfeed->folder->display_name,newsfeed->activity->page_id_from,newsfeed->comment_count,can_edit,newsfeed->activity->get,view_type,newsfeed->page_id_to,page_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_full_list.php' , 'view_type,newsfeeds'),
			( NULL , 'modules/newsfeed/views/source.php' , 'source,category_type'),
			( NULL , 'modules/newsfeed/views/activity.php' , 'view,activity->type,activity->url,activity->thumb,activity->user_id_to,activity->user_from,activity->user_from->url,activity->user_from->avatar_small,activity->user_id_from,activity->id,stage,activity->user_from->full_name,activity->user_from->first_name,activity->text,activity->time'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline_new_comment.php' , 'newsfeed->type,newsfeed->activity->photo_id,newsfeed->activity->link_id,recent_comment->user_from->avatar_small,recent_comment->user_from->url,recent_comment->user_from->first_name,recent_comment->user_from->last_name,recent_comment->comment,recent_comment->time,recent_comment,recent_comment->comment_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_item_full.php' , 'view_type,fvalue[''data''],fvalue[''type''],fvalue[''newsfeed_id''],fvalue[''page_id_to''],can_comment,fvalue[''relation''],ajax,like_value[''user_id''],news_aray[''page_id_to''],news_aray[''user_id_from''],page_id'),
			( NULL , 'modules/newsfeed/views/filter_types_menu.php' , 'value'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline.php' , 'newsfeed->up_count,newsfeed->activity->likes,f_count,view,newsfeed->type,newsfeed->link_type,newsfeed->activity->photo_id,newsfeed->activity->link_id,newsfeed->newsfeed_id,newsfeed->activity->link,newsfeed->user_from->id,newsfeed->user_from->url,newsfeed->user_from->avatar_preview,newsfeed,newsfeed->link_type_class,newsfeed->page_id_to,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,newsfeed->folder_id,newsfeed->folder->folder_name,newsfeed->folder->url,newsfeed->folder->display_name,newsfeed->user_from->first_name,newsfeed->user_from->last_name,newsfeed->activity->time,newsfeed->activity->img_thumb,newsfeed->activity->img_width,newsfeed->activity->img_height,newsfeed->activity->media,newsfeed->activity->content,like_data,newsfeed->activity->text,newsfeed->activity_id,newsfeed->activity->page_id_from'),
			( NULL , 'modules/newsfeed/views/newsfeed_home_interests.php' , 'fvalue,fvalue[''newsfeed_id''],fvalue[''type''],can_comment,fvalue[''relation''],like_value[''user_id''],fvalue[''page_name''],fvalue[''uri_name''],fvalue[''page_id_to''],like_value,like_value[''type''],like_value[''page_id''],ajax,view'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline_edit.php' , 'newsfeed->newsfeed_id,newsfeed->type,newsfeed->activity->title,newsfeed->activity->caption,newsfeed->activity->link,page_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_link_popup.php' , 'signup_popup_disable,fb_friends,fb_newsfeeds,newsfeed,view_type,newsfeed->up_count,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,can_edit,newsfeed->url,full_drop_page'),
			( NULL , 'modules/newsfeed/views/newsfeed.php' , 'view_type,page_id,post_type,profile_id,fvalue[''data'']'),
			( NULL , 'modules/newsfeed/views/newsfeed_tile_edit.php' , 'newsfeed->newsfeed_id,newsfeed->type,newsfeed->activity->title,newsfeed->activity->caption,page_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_popup_edit.php' , 'newsfeed->newsfeed_id,newsfeed->activity->title,newsfeed->activity->caption,newsfeed->activity->text,newsfeed->activity->link'),
			( NULL , 'modules/newsfeed/views/newsfeed_mag.php' , 'view_type,page_id,post_type,profile_id,fvalue[''data''],fvalue[''type''],fvalue[''newsfeed_id''],fvalue[''page_id_to''],entity_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline_new_list.php' , 'cache_name,is_landingpage,newsfeeds,page_id,view'),
			( NULL , 'modules/newsfeed/views/newsfeed_card_list.php' , 'newsfeeds,page_id,view,category_type,topic_id'),
			( NULL , 'modules/newsfeed/views/activity_list.php' , 'ticker,activity,profile_user->first_name,page'),
			( NULL , 'modules/newsfeed/views/view_modes_menu.php' , 'url'),
			( NULL , 'modules/newsfeed/views/newsfeed_timeline_new.php' , 'newsfeed->up_count,newsfeed->activity->likes,f_count,view,newsfeed->type,newsfeed->link_type,newsfeed->activity->photo_id,newsfeed->activity->link_id,newsfeed->newsfeed_id,is_landingpage,newsfeed->activity->link,newsfeed->activity->source,newsfeed,newsfeed->activity->text,newsfeed->link_type_class,newsfeed->activity->img_width,newsfeed->activity->img_height,newsfeed->activity->img_thumb,newsfeed->activity->media,newsfeed->activity->content,newsfeed->activity_id,newsfeed->activity->page_id_from,newsfeed->page_id_to,newsfeed->user_id_to,newsfeed->comment_count,can_edit,newsfeed->user_from->id,newsfeed->user_from->url,newsfeed->user_from->avatar_small,newsfeed->user_from->full_name,newsfeed->page_to->official_url,newsfeed->page_to->uri_name,newsfeed->page_to->page_id,newsfeed->page_to->page_name,newsfeed->folder_id,newsfeed->folder->folder_name,newsfeed->folder->url,newsfeed->folder->display_name,newsfeed->time,newsfeed->activity->caption,newsfeed->folder->private,newsfeed->user_from->first_name,newsfeed->user_from->last_name,newsfeed->collect_count,newsfeed->activity->get,view_type,like_data_comm'),
			( NULL , 'modules/newsfeed/views/newsfeed_grid.php' , 'view_type,page_id,post_type,profile_id,fvalue[''data''],fvalue[''type''],fvalue[''newsfeed_id''],fvalue[''page_id_to''],entity_id'),
			( NULL , 'modules/newsfeed/views/newsfeed_tile_new_comment.php' , 'recent_comment->user_from->avatar_small,newsfeed->type,newsfeed->activity->photo_id,newsfeed->activity->link_id,recent_comment->comment_id,newsfeed_id,recent_comment->user_from->url,recent_comment->user_from->first_name,recent_comment->user_from->last_name,recent_comment->comment'),
			( NULL , 'modules/google_image_search/views/getimages.php' , 'results,page_id,image->thumb,image->img,image->title,page'),
			( NULL , 'modules/google_image_search/views/gis_view.php' , 'page_name,page_id'),
			( NULL , 'modules/embed/views/collection_overview.php' , 'folder->url,folder->folder_id,folder->folder_name,folder->display_name,folder->private,folder->recent_newsfeeds,item->type,item->link_type,item->text,item->title,item->bigimg,item->img,folder->folder_contributors[0]->user_id,transfer_fb_msg,transfer_twitter_msg,folder->drops,folder->total_hits'),
			( NULL , 'modules/admin/views/folders/select_folder_view.php' , 'folders,folder'),
			( NULL , 'modules/admin/views/beanstalk_jobs.php' , 'limit,flots,flot,flot[''start_delay''],flot[''processing_time'']'),
			( NULL , 'modules/admin/views/list_sxsw_link_urls.php' , 'filters,list_fields,data,data->get_all,type,data->pagination->create_links'),
			( NULL , 'modules/admin/views/forms.php' , 'fields,type'),
			( NULL , 'modules/admin/views/stats.php' , 'method,metric,dimension,url'),
			( NULL , 'modules/admin/views/filters.php' , 'filters,type'),
			( NULL , 'modules/admin/views/source_stats.php' , 'url'),
			( NULL , 'modules/admin/views/alpha_user.php' , 'filters,list_fields,data,type,list_actions'),
			( NULL , 'modules/admin/views/users/subscription_view.php' , 'filters,list_fields,items,type'),
			( NULL , 'modules/admin/views/users/list.php' , 'filters,list_fields,type,order,data,data->get_all,list_actions,data->pagination->create_links'),
			( NULL , 'modules/admin/views/dashboard.php' , 'data[''num_users''],data[''act_users''],data[''fb''],data[''tw''],data[''shared_links''],data[''uniq_domains''],data[''folders_count''],data[''private_count''],data[''public_count''],data[''avg_links''],data[''comments_count''],data[''likes_count''],data[''redrop_count''],data[''users_shares''],data[''users_shares''][\$i],data[''most_links''],data[''most_links''][\$i],data[''interests_most_links''],data[''interests_most_links''][\$i],data[''image_count''],data[''clip_count''],data[''screenshot_count''],data[''video_count''],data[''text_count'']'),
			( NULL , 'modules/admin/views/links/sources.php' , 'sources'),
			( NULL , 'modules/admin/views/stats/chart_bar.php' , 'metric,dimension,url,data'),
			( NULL , 'modules/admin/views/stats/links.php' , 'types,sources,val[''label''],val[''data'']'),
			( NULL , 'modules/admin/views/stats/chart_line.php' , 'data_url,metric,dimension,url,unit'),
			( NULL , 'modules/admin/views/stats/chart_pie.php' , 'metric,dimension,url,data'),
			( NULL , 'modules/admin/views/stats/users.php' , 'gender,linked'),
			( NULL , 'modules/admin/views/stats/sources.php' , 'keywords,val[0],val[1],landing_pages,val'),
			( NULL , 'modules/admin/views/stats/content.php' , 'page_views,val[0],val[1]'),
			( NULL , 'modules/admin/views/stats/index.php' , 'page'),
			( NULL , 'modules/admin/views/form.php' , 'form_fields,sub_form[0],sub_form,list_fields,data,type,edit_actions,data->\$primary_key,data->\$field'),
			( NULL , 'modules/admin/views/list.php' , 'filters,forms,filter_tabs,filter,filter_token,list_collection_actions,list_fields,type,order,foreign_fields,data,data->get_all,list_actions,data->pagination->create_links'),
			( NULL , 'modules/signup/views/twitter_logged.php' , 'user_info'),
			( NULL , 'modules/signup/views/register.php' , 'step,from,skip_registration,user_id,gender,dob_m,dob_d,dob_y,first_name,last_name,email_address,password,genders,months,days,years'),
			( NULL , 'modules/signup/views/hometest.php' , 'e'),
			( NULL , 'modules/signup/views/fandrop_aftersignup.php' , 'email_count'),
			( NULL , 'modules/signup/views/share_on_fb.php' , 'head_content,folder_url'),
			( NULL , 'modules/signup/views/email_form.php' , 'user_id,username,email_address,password,first_name,last_name,fb_id'),
			( NULL , 'modules/signup/views/grabbed_info_basic.php' , 'fb_friends,power_users,fb_newsfeeds,v->folder_name,v->url'),
			( NULL , 'modules/signup/views/category.php' , 'topics'),
			( NULL , 'modules/signup/views/register_form.php' , 'beta_id,fb_id,twitter_id,user_id,username,email_address,first_name,last_name,password'),
			( NULL , 'modules/signup/views/create_collections.php' , 'collections'),
			( NULL , 'modules/signup/views/add_user_info.php' , 'user_id'),
			( NULL , 'modules/signup/views/twitter_form.php' , 'beta_id,fb_id,twitter_id,user_id,first_name,last_name,username,email_address'),
			( NULL , 'modules/signup/views/request_invite.php' , 'signinUrl'),
			( NULL , 'modules/signup/views/more_info.php' , 'fb_id,hide_twitter,hide_fb,fb_pages,twitter_id,twitter_pages,transfer_link_msg,fb_friends,twitter_friends'),
			( NULL , 'modules/signup/views/grabbed_info.php' , 'collections,friends,power_users,links,v->folder_name,v->url'),
			( NULL , 'modules/signup/views/basic_info.php' , 'username,value,beta_id,fb_id,twitter_id,loginUrl,user_id,first_name,last_name,email_address,password'),
			( NULL , 'modules/signup/views/fandrop_signup.php' , 'error_msg'),
			( NULL , 'modules/tools/views/fetch_link.php' , 'rel,base,rel[0],host\$path,pattern,content,match,match[1],key2,val2,width,height'),
			( NULL , 'modules/tools/views/fetch.php' , 'rel,base,rel[0],host\$path,pattern,content,match,match[1],key2,val2'),
			( NULL , 'modules/footer/views/about.php' , 'stage,include_file'),
			( NULL , 'modules/forget_password/views/forgetpassword_view.php' , 'error'),
			( NULL , 'modules/forget_password/views/resetpassword_view.php' , 'id,error_msg'),
			( NULL , 'modules/message/views/msg_inbox_entry.php' , 'message_thread[0],receiver,v[''id''],v[''uri_name''],v[''first_name''],v[''last_name''],receiver[count'),
			( NULL , 'modules/message/views/recipients.php' , 'recipients,v[''id''],v[''uri_name''],v[''first_name''],v[''last_name'']'),
			( NULL , 'modules/message/views/msg_inbox.php' , 'title_info,inbox,value[''display_status''],value[''thread_id''],value[''users''],v[''user_id''],v[''uri_name''],v[''first_name''],v[''last_name''],value[''users''][count,value[''from''],value[''uri_name''],value[''first_name''],value[''last_name''],value[''time''],value[''msg_body''],msg_name,msg_reply_id,msg_class,msg_body'),
			( NULL , 'modules/message/views/msg_thread_entry.php' , 'message_thread[0],thread_id'),
			( NULL , 'modules/message/views/msg_thread.php' , 'full_name,v[''uri_name''],v[''name''],v,message_thread,value[''display_status''],value[''first_name''],value[''last_name''],value[''from''],value[''uri_name''],value[''time''],value[''msg_body''],value[''msg_id''],to_user_id,user'),
			( NULL , 'modules/profile/views/profile_types.php' , 'profile_id,category_type'),
			( NULL , 'modules/profile/views/view_interests.php' , 'profile_user->id,your_interests,my_interests,page_ids'),
			( NULL , 'modules/profile/views/profile_top.php' , 'hide_userinfo,hide_vibes,hide_tabs,profile_user->url,profile_user->full_name,profile_user->verified,profile_user->id,check_friends,profile_view,profile_user->user_stats[0]->collections,profile_user->drops_url,profile_user->user_stats[0]->total_drops,profile_user->likes_url,profile_user->user_stats[0]->likes,profile_user->mentions_url,profile_user->user_stats[0]->mention,profile_user->comments_url,profile_user->user_stats[0]->comments,profile_user->library_url,disable_drop_filter,profile_user->images_url,profile_user->user_stats[0]->image,profile_user->clips_url,profile_user->user_stats[0]->clip,profile_user->user_stats[0]->screenshot,profile_user->videos_url,profile_user->user_stats[0]->video,profile_user->texts_url,profile_user->user_stats[0]->text,like_filter,profile_user->fb_id,loginUrl,profile_user->twitter_id'),
			( NULL , 'modules/profile/views/view_more_interests.php' , 'your_interests,item->page->page_id,item->page->thumbnail,item->page->interest_id,item->page->uri_name,my_interests,owner_priv,admin_priv,item->page->page_name,item->page->hits,item->page->get,value,value->user->avatar_badge,value->user->id,value->user->gender,value->user->first_name,value->user->last_name,value->user->uri_name,value->user->url,page_ids'),
			( NULL , 'modules/profile/views/edit_personal_info.php' , 'month,day,year,m_gender,f_gender,info[0][''about''],quotes[0][''quotes''],info[0][''color_id''],contact[0][''email''],contact[0][''im''],contact[0][''phone''],contact[0][''address''],schools,school[''id''],school[''school_id''],school[''name''],school[''major_data''],v[''major_id''],v[''major''],school[''year''],years,school[''major''],add_info_groups[''color'']'),
			( NULL , 'modules/profile/views/profile_main.php' , 'include_file,profile_id,peopleshouldknow'),
			( NULL , 'modules/profile/views/profile.php' , 'is_ajax,inner_view,profile_user->id,stage,profile_user->avatar_thumb,hide_main_border,hide_userinfo,hide_tabs,hide_lists,profile_view,profile_user->url,collection_dropdown,profile_user->drops_url,profile_user->likes_url,category_type,profile_user->uri_name,profile_user->first_name,isFollowingFollowerPage,loop_tabs,peopleshouldknow'),
			( NULL , 'modules/profile/views/connections_list.php' , 'autoscroll,new_connection_list,type,sub_title,user_type,item->,item,your_connection_ids,loadmore,new_list_my_pages,item[''thumbnail''],item[''interest_id''],item[''uri_name''],item[''page_id''],item[''page_name''],new_list_pages_made'),
			( NULL , 'modules/profile/views/account.php' , 'first_name,last_name,user->uri_name,loginUrl,email_settings->message,email_settings->comment,email_settings->up_link,email_settings->up_comment,email_settings->connection,email_settings->follow_folder,email_settings->collaboration,email_settings->newsletter,status'),
			( NULL , 'modules/profile/views/user_topics.php' , 'topics,v[''topic_name''],v[''topic_id'']'),
			( NULL , 'modules/profile/views/gmail.php' , 'res,results'),
			( NULL , 'modules/profile/views/user_info.php' , 'info,edit_info_url,info[0][''birthday''],info[0][''gender''],info[0][''about''],info[0][''quotes''],info[0][''color_id''],info[0][''im''],info[0][''phone''],info[0][''address''],schools,profile_user->id,real_id,sv[''name''],sv[''year''],sv[''major''],query->num_rows,query->result,link_query->num_rows,link_query->result'),
			( NULL , 'modules/profile/views/invite_gmail.php' , 'messages[\$i][''email''],messages[\$i][''msg'']'),
			( NULL , 'modules/profile/views/profile_drops.php' , 'profile_uri,profile_id,category_type'),
			( NULL , 'modules/profile/views/profile_right.php' , 'logger,profile_user->avatar_thumb,hide_sidebar_details,profile_user->id,profile_user->following,profile_user->follower,stage'),
			( NULL , 'modules/profile/views/invite_page.php' , 'messages[\$i][''email''],messages[\$i][''msg'']'),
			( NULL , 'modules/profile/views/my_interests_edit.php' , 'vibe_question,vibe_info,row[''page_id''],row[''thumbnail''],row[''page_name''],questions,v[''q_id''],v[''question''],v[''answers''],row,share_list,v,v[''page_id''],v[''page_name''],v[''owner''],vv[''id''],vv[''gender''],vv[''description''],v[''shared''],vv,vv[''first_name''],vv[''last_name''],all_interests,item[''thumbnail''],item[''interest_id''],item[''uri_name''],item[''page_id''],item[''page_name'']'),
			( NULL , 'modules/profile/views/edit_picture.php' , 'user->avatar_thumb'),
			( NULL , 'modules/profile/views/yahoo_email.php' , 'res,results'),
			( NULL , 'modules/profile/views/fb_friends_list.php' , 'results'),
			( NULL , 'modules/profile/views/friends_from_invite.php' , 'friends,following_ids'),
			( NULL , 'modules/profile/views/new_school_entry.php' , 'schools,school[''id''],school[''school_id''],school[''name''],school[''major_data''],v[''major_id''],v[''major''],school[''year''],years,school[''major'']'),
			( NULL , 'modules/link/views/bar.php' , 'url,interests,folders'),
			( NULL , 'modules/facebook_app/views/timeline_app.php' , 'exc,e,first_visit'),
			( NULL , 'modules/help/views/walkthrough.php' , 'stage'),
			( NULL , 'modules/folder/views/create_collection_popup.php' , 'default_topics,followings,button'),
			( NULL , 'modules/folder/views/folders.php' , 'profile_id,folders,fv->private,fv->user_id,fv->folder_id,fv->folder_name,fv->url,fv->get,item->link_type,item->type,item->data[''s3_thumb''],item->activity->caption,item,fv->folder_contributors[0]->user_id,transfer_fb_msg,transfer_twitter_msg,fv->drops,fv->editable,fv->following'),
			( NULL , 'modules/folder/views/folder_more_newsfeed.php' , 'view_type,folder_data,fvalue[''time''],fvalue[''data''],fvalue[''newsfeed_id''],category_type'),
			( NULL , 'modules/folder/views/folder_list.php' , 'collections_cache,folders,profile_id,fv->private,fv->user_id,fv->folder_id,fv->folder_name,fv->url,fv->recent_newsfeeds,item->link_type,item->type,item->text,item->title,item->bigimg,item->img,fv->folder_contributors[0]->user_id,transfer_fb_msg,transfer_twitter_msg,fv->drops,fv->total_hits,fv->editable,fv->following,offset'),
			( NULL , 'modules/folder/views/folder_follow_button.php' , 'folder_id'),
			( NULL , 'modules/folder/views/folder_main.php' , 'profile_id,folders,fv->private,fv->user_id,fv->folder_id,fv->folder_name,fv->display_name,fv->url,fv->recent_newsfeeds,item->type,item->link_type,item->text,item->title,item->bigimg,item->img,fv->folder_contributors[0]->user_id,transfer_fb_msg,transfer_twitter_msg,fv->drops,fv->total_hits,fv->editable,fv->following,category_type'),
			( NULL , 'modules/folder/views/folder_new_entry.php' , 'folder_info->folder_id,folder_info->folder_uri,folder_info->folder_name,folder_info->private,user_url_name'),
			( NULL , 'modules/folder/views/folder.php' , 'stage,folder_info->folder_id,folder_info->url,folder_info->private,folder_info->user_id,folder_info->get,folder_info->folder_name,collaborators,folder_info->topic_folders,transfer_msg,back_url,profile_id,folder_info'),
			( NULL , 'modules/folder/views/collect.php' , 'folders_for_collect,folders_dropdown'),
			( NULL , 'modules/folder/views/folder_following_button.php' , 'folder_id'),
			( NULL , 'modules/folder/views/profile_collection.php' , 'profile_id,folders_dropdown'),
			( NULL , 'modules/folder/views/folder_top.php' , 'hide_userinfo,hide_vibes,hide_tabs,folder_info->folder_name,folder_info->user->avatar_preview,folder_info->user->url,profile_user->full_name,profile_id,check_friends,profile_user->following,profile_user->follower,folder_info->drops,hits'),
			( NULL , 'modules/notification/views/notifications.php' , 'notifications,notifications_color,notifications_short'),
			( NULL , 'modules/notification/views/notifications_groups.php' , 'grouped_notifications,notifications'),
			( NULL , 'modules/notification/views/notifications_list.php' , 'grouped_notifications'),
			( NULL , 'modules/bookmarklet/views/popup.php' , 'url,page_id,folders,folder[''id''],folder[''class''],folder[''name''],interests,value'),
			( NULL , 'modules/bookmarklet/views/bar.php' , 'internal,folders,recent,interests'),
			( NULL , 'modules/bookmarklet/views/snapshot.php' , 'item->activity->trimmed_left,item->activity->trimmed_top,content'),
			( NULL , 'modules/bookmarklet/views/login.php' , 'display,message'),
			( NULL , 'modules/bookmarklet/views/success.php' , 'newsfeed->newsfeed_id,newsfeed->folder->url,newsfeed->folder->folder_name,newsfeed->url'),
			( NULL , 'modules/bookmarklet/views/edit_post.php' , 'feed->activity->link_id,feed->activity->title,feed->link_type,feed->activity->thumb,feed->activity->content,folders,feed->folder_id'),
			( NULL , 'modules/bookmarklet/views/embed_popup.php' , 'folders,folder[''id''],folder[''class''],folder[''name'']')");
	}

	public function down()
	{
	}
}
